// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    BatteryInfo,
    CommandResult,
    CpuUsageInfo,
    Device,
    DeviceDetailInfo,
    MemoryInfo,
    NetworkInfo,
    Platform,
    StorageInfo,
    SystemRuntime
} from "./models.js";

import * as $models from "./models.js";

/**
 * SystemProperties 系统属性
 * @typedef {$models.SystemProperties} SystemProperties
 */
