// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BatteryInfo 电池信息
 */
export class BatteryInfo {
    /**
     * Creates a new BatteryInfo instance.
     * @param {Partial<BatteryInfo>} [$$source = {}] - The source object to create the BatteryInfo.
     */
    constructor($$source = {}) {
        if (!("capacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacity"] = 0;
        }
        if (!("temperature" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["temperature"] = 0;
        }
        if (!("voltage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["voltage"] = 0;
        }
        if (!("chargingStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chargingStatus"] = "";
        }
        if (!("pluggedType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluggedType"] = "";
        }
        if (!("technology" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["technology"] = "";
        }
        if (!("health" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["health"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatteryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatteryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatteryInfo(/** @type {Partial<BatteryInfo>} */($$parsedSource));
    }
}

/**
 * CommandResult 命令执行结果
 */
export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

/**
 * CpuUsageInfo CPU 使用信息
 */
export class CpuUsageInfo {
    /**
     * Creates a new CpuUsageInfo instance.
     * @param {Partial<CpuUsageInfo>} [$$source = {}] - The source object to create the CpuUsageInfo.
     */
    constructor($$source = {}) {
        if (!("usagePercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usagePercent"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user"] = 0;
        }
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["system"] = 0;
        }
        if (!("idle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idle"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CpuUsageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CpuUsageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CpuUsageInfo(/** @type {Partial<CpuUsageInfo>} */($$parsedSource));
    }
}

/**
 * Device 统一设备信息
 */
export class Device {
    /**
     * Creates a new Device instance.
     * @param {Partial<Device>} [$$source = {}] - The source object to create the Device.
     */
    constructor($$source = {}) {
        if (!("connectKey" in $$source)) {
            /**
             * 设备标识符
             * @member
             * @type {string}
             */
            this["connectKey"] = "";
        }
        if (!("connectionType" in $$source)) {
            /**
             * 连接类型：USB 或 TCP
             * @member
             * @type {string}
             */
            this["connectionType"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 连接状态
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 设备名称
             * @member
             * @type {string | undefined}
             */
            this["deviceName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 产品名称
             * @member
             * @type {string | undefined}
             */
            this["productName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 产品型号
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 显示名称
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (!("platform" in $$source)) {
            /**
             * 平台：harmonyos 或 android
             * @member
             * @type {Platform}
             */
            this["platform"] = Platform.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Device}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Device(/** @type {Partial<Device>} */($$parsedSource));
    }
}

/**
 * DeviceDetailInfo 设备详细信息
 */
export class DeviceDetailInfo {
    /**
     * Creates a new DeviceDetailInfo instance.
     * @param {Partial<DeviceDetailInfo>} [$$source = {}] - The source object to create the DeviceDetailInfo.
     */
    constructor($$source = {}) {
        if (!("productName" in $$source)) {
            /**
             * 基本信息
             * @member
             * @type {string}
             */
            this["productName"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("brand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brand"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("deviceType" in $$source)) {
            /**
             * 设备形态（手机/平板等）
             * @member
             * @type {string}
             */
            this["deviceType"] = "";
        }
        if (!("serialNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serialNumber"] = "";
        }
        if (!("osName" in $$source)) {
            /**
             * 系统信息
             * @member
             * @type {string}
             */
            this["osName"] = "";
        }
        if (!("osVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osVersion"] = "";
        }
        if (!("apiVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiVersion"] = "";
        }
        if (!("softwareVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["softwareVersion"] = "";
        }
        if (!("securityPatch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["securityPatch"] = "";
        }
        if (!("kernelVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kernelVersion"] = "";
        }
        if (!("cpuAbi" in $$source)) {
            /**
             * 硬件信息
             * @member
             * @type {string}
             */
            this["cpuAbi"] = "";
        }
        if (!("hardwareVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hardwareVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceDetailInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceDetailInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceDetailInfo(/** @type {Partial<DeviceDetailInfo>} */($$parsedSource));
    }
}

/**
 * MemoryInfo 内存信息
 */
export class MemoryInfo {
    /**
     * Creates a new MemoryInfo instance.
     * @param {Partial<MemoryInfo>} [$$source = {}] - The source object to create the MemoryInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("free" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["free"] = 0;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["available"] = 0;
        }
        if (!("cached" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cached"] = 0;
        }
        if (!("usedPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usedPercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryInfo(/** @type {Partial<MemoryInfo>} */($$parsedSource));
    }
}

/**
 * NetworkInfo 网络信息
 */
export class NetworkInfo {
    /**
     * Creates a new NetworkInfo instance.
     * @param {Partial<NetworkInfo>} [$$source = {}] - The source object to create the NetworkInfo.
     */
    constructor($$source = {}) {
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("ipAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ipAddress"] = "";
        }
        if (!("macAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["macAddress"] = "";
        }
        if (!("netmask" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["netmask"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInfo(/** @type {Partial<NetworkInfo>} */($$parsedSource));
    }
}

/**
 * Platform 设备平台类型
 * @readonly
 * @enum {string}
 */
export const Platform = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlatformHarmonyOS: "harmonyos",
    PlatformAndroid: "android",
};

/**
 * StorageInfo 存储信息
 */
export class StorageInfo {
    /**
     * Creates a new StorageInfo instance.
     * @param {Partial<StorageInfo>} [$$source = {}] - The source object to create the StorageInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["total"] = "";
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["used"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["available"] = "";
        }
        if (!("usedPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usedPercent"] = 0;
        }
        if (!("mountPoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mountPoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageInfo(/** @type {Partial<StorageInfo>} */($$parsedSource));
    }
}

/**
 * SystemProperties 系统属性
 * @typedef {{ [_ in string]?: string }} SystemProperties
 */

/**
 * SystemRuntime 系统运行状态
 */
export class SystemRuntime {
    /**
     * Creates a new SystemRuntime instance.
     * @param {Partial<SystemRuntime>} [$$source = {}] - The source object to create the SystemRuntime.
     */
    constructor($$source = {}) {
        if (!("uptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }
        if (!("loadAverage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["loadAverage"] = "";
        }
        if (!("currentTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemRuntime instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemRuntime}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemRuntime(/** @type {Partial<SystemRuntime>} */($$parsedSource));
    }
}
