// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: scrcpy.proto

package scrcpyproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScrcpyService_OnStart_FullMethodName           = "/ScrcpyService/onStart"
	ScrcpyService_OnEnd_FullMethodName             = "/ScrcpyService/onEnd"
	ScrcpyService_OnRequestIDRFrame_FullMethodName = "/ScrcpyService/onRequestIDRFrame"
)

// ScrcpyServiceClient is the client API for ScrcpyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrcpyServiceClient interface {
	OnStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplyMessage], error)
	OnEnd(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReplyEndMessage, error)
	OnRequestIDRFrame(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReplyEndMessage, error)
}

type scrcpyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrcpyServiceClient(cc grpc.ClientConnInterface) ScrcpyServiceClient {
	return &scrcpyServiceClient{cc}
}

func (c *scrcpyServiceClient) OnStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReplyMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScrcpyService_ServiceDesc.Streams[0], ScrcpyService_OnStart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ReplyMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScrcpyService_OnStartClient = grpc.ServerStreamingClient[ReplyMessage]

func (c *scrcpyServiceClient) OnEnd(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReplyEndMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyEndMessage)
	err := c.cc.Invoke(ctx, ScrcpyService_OnEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scrcpyServiceClient) OnRequestIDRFrame(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ReplyEndMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyEndMessage)
	err := c.cc.Invoke(ctx, ScrcpyService_OnRequestIDRFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrcpyServiceServer is the server API for ScrcpyService service.
// All implementations must embed UnimplementedScrcpyServiceServer
// for forward compatibility.
type ScrcpyServiceServer interface {
	OnStart(*Empty, grpc.ServerStreamingServer[ReplyMessage]) error
	OnEnd(context.Context, *Empty) (*ReplyEndMessage, error)
	OnRequestIDRFrame(context.Context, *Empty) (*ReplyEndMessage, error)
	mustEmbedUnimplementedScrcpyServiceServer()
}

// UnimplementedScrcpyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScrcpyServiceServer struct{}

func (UnimplementedScrcpyServiceServer) OnStart(*Empty, grpc.ServerStreamingServer[ReplyMessage]) error {
	return status.Error(codes.Unimplemented, "method OnStart not implemented")
}
func (UnimplementedScrcpyServiceServer) OnEnd(context.Context, *Empty) (*ReplyEndMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method OnEnd not implemented")
}
func (UnimplementedScrcpyServiceServer) OnRequestIDRFrame(context.Context, *Empty) (*ReplyEndMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method OnRequestIDRFrame not implemented")
}
func (UnimplementedScrcpyServiceServer) mustEmbedUnimplementedScrcpyServiceServer() {}
func (UnimplementedScrcpyServiceServer) testEmbeddedByValue()                       {}

// UnsafeScrcpyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrcpyServiceServer will
// result in compilation errors.
type UnsafeScrcpyServiceServer interface {
	mustEmbedUnimplementedScrcpyServiceServer()
}

func RegisterScrcpyServiceServer(s grpc.ServiceRegistrar, srv ScrcpyServiceServer) {
	// If the following call panics, it indicates UnimplementedScrcpyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScrcpyService_ServiceDesc, srv)
}

func _ScrcpyService_OnStart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScrcpyServiceServer).OnStart(m, &grpc.GenericServerStream[Empty, ReplyMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScrcpyService_OnStartServer = grpc.ServerStreamingServer[ReplyMessage]

func _ScrcpyService_OnEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrcpyServiceServer).OnEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrcpyService_OnEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrcpyServiceServer).OnEnd(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScrcpyService_OnRequestIDRFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrcpyServiceServer).OnRequestIDRFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScrcpyService_OnRequestIDRFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrcpyServiceServer).OnRequestIDRFrame(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrcpyService_ServiceDesc is the grpc.ServiceDesc for ScrcpyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrcpyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ScrcpyService",
	HandlerType: (*ScrcpyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "onEnd",
			Handler:    _ScrcpyService_OnEnd_Handler,
		},
		{
			MethodName: "onRequestIDRFrame",
			Handler:    _ScrcpyService_OnRequestIDRFrame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "onStart",
			Handler:       _ScrcpyService_OnStart_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scrcpy.proto",
}
