// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: scrcpy.proto

package scrcpyproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_scrcpy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_scrcpy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_scrcpy_proto_rawDescGZIP(), []int{0}
}

type ParamValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Values:
	//
	//	*ParamValue_ValInt
	//	*ParamValue_ValDouble
	//	*ParamValue_ValString
	//	*ParamValue_ValBool
	//	*ParamValue_ValBytes
	//	*ParamValue_ValFloat
	Values        isParamValue_Values `protobuf_oneof:"values"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamValue) Reset() {
	*x = ParamValue{}
	mi := &file_scrcpy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamValue) ProtoMessage() {}

func (x *ParamValue) ProtoReflect() protoreflect.Message {
	mi := &file_scrcpy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamValue.ProtoReflect.Descriptor instead.
func (*ParamValue) Descriptor() ([]byte, []int) {
	return file_scrcpy_proto_rawDescGZIP(), []int{1}
}

func (x *ParamValue) GetValues() isParamValue_Values {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ParamValue) GetValInt() int64 {
	if x != nil {
		if x, ok := x.Values.(*ParamValue_ValInt); ok {
			return x.ValInt
		}
	}
	return 0
}

func (x *ParamValue) GetValDouble() float64 {
	if x != nil {
		if x, ok := x.Values.(*ParamValue_ValDouble); ok {
			return x.ValDouble
		}
	}
	return 0
}

func (x *ParamValue) GetValString() string {
	if x != nil {
		if x, ok := x.Values.(*ParamValue_ValString); ok {
			return x.ValString
		}
	}
	return ""
}

func (x *ParamValue) GetValBool() bool {
	if x != nil {
		if x, ok := x.Values.(*ParamValue_ValBool); ok {
			return x.ValBool
		}
	}
	return false
}

func (x *ParamValue) GetValBytes() []byte {
	if x != nil {
		if x, ok := x.Values.(*ParamValue_ValBytes); ok {
			return x.ValBytes
		}
	}
	return nil
}

func (x *ParamValue) GetValFloat() float32 {
	if x != nil {
		if x, ok := x.Values.(*ParamValue_ValFloat); ok {
			return x.ValFloat
		}
	}
	return 0
}

type isParamValue_Values interface {
	isParamValue_Values()
}

type ParamValue_ValInt struct {
	ValInt int64 `protobuf:"varint,1,opt,name=val_int,json=valInt,proto3,oneof"`
}

type ParamValue_ValDouble struct {
	ValDouble float64 `protobuf:"fixed64,2,opt,name=val_double,json=valDouble,proto3,oneof"`
}

type ParamValue_ValString struct {
	ValString string `protobuf:"bytes,3,opt,name=val_string,json=valString,proto3,oneof"`
}

type ParamValue_ValBool struct {
	ValBool bool `protobuf:"varint,4,opt,name=val_bool,json=valBool,proto3,oneof"`
}

type ParamValue_ValBytes struct {
	ValBytes []byte `protobuf:"bytes,5,opt,name=val_bytes,json=valBytes,proto3,oneof"`
}

type ParamValue_ValFloat struct {
	ValFloat float32 `protobuf:"fixed32,6,opt,name=val_float,json=valFloat,proto3,oneof"`
}

func (*ParamValue_ValInt) isParamValue_Values() {}

func (*ParamValue_ValDouble) isParamValue_Values() {}

func (*ParamValue_ValString) isParamValue_Values() {}

func (*ParamValue_ValBool) isParamValue_Values() {}

func (*ParamValue_ValBytes) isParamValue_Values() {}

func (*ParamValue_ValFloat) isParamValue_Values() {}

type ReplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ReplyType     int32                  `protobuf:"varint,2,opt,name=reply_type,json=replyType,proto3" json:"reply_type,omitempty"`
	Payload       map[string]*ParamValue `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_scrcpy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scrcpy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_scrcpy_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ReplyMessage) GetReplyType() int32 {
	if x != nil {
		return x.ReplyType
	}
	return 0
}

func (x *ReplyMessage) GetPayload() map[string]*ParamValue {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReplyEndMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyEndMessage) Reset() {
	*x = ReplyEndMessage{}
	mi := &file_scrcpy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyEndMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyEndMessage) ProtoMessage() {}

func (x *ReplyEndMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scrcpy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyEndMessage.ProtoReflect.Descriptor instead.
func (*ReplyEndMessage) Descriptor() ([]byte, []int) {
	return file_scrcpy_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyEndMessage) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_scrcpy_proto protoreflect.FileDescriptor

const file_scrcpy_proto_rawDesc = "" +
	"\n" +
	"\fscrcpy.proto\"\a\n" +
	"\x05Empty\"\xce\x01\n" +
	"\n" +
	"ParamValue\x12\x19\n" +
	"\aval_int\x18\x01 \x01(\x03H\x00R\x06valInt\x12\x1f\n" +
	"\n" +
	"val_double\x18\x02 \x01(\x01H\x00R\tvalDouble\x12\x1f\n" +
	"\n" +
	"val_string\x18\x03 \x01(\tH\x00R\tvalString\x12\x1b\n" +
	"\bval_bool\x18\x04 \x01(\bH\x00R\avalBool\x12\x1d\n" +
	"\tval_bytes\x18\x05 \x01(\fH\x00R\bvalBytes\x12\x1d\n" +
	"\tval_float\x18\x06 \x01(\x02H\x00R\bvalFloatB\b\n" +
	"\x06values\"\xc0\x01\n" +
	"\fReplyMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"reply_type\x18\x02 \x01(\x05R\treplyType\x124\n" +
	"\apayload\x18\x03 \x03(\v2\x1a.ReplyMessage.PayloadEntryR\apayload\x1aG\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.ParamValueR\x05value:\x028\x01\")\n" +
	"\x0fReplyEndMessage\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\x85\x01\n" +
	"\rScrcpyService\x12\"\n" +
	"\aonStart\x12\x06.Empty\x1a\r.ReplyMessage0\x01\x12!\n" +
	"\x05onEnd\x12\x06.Empty\x1a\x10.ReplyEndMessage\x12-\n" +
	"\x11onRequestIDRFrame\x12\x06.Empty\x1a\x10.ReplyEndMessageB#Z!Hadice/backend/hypium/scrcpyprotob\x06proto3"

var (
	file_scrcpy_proto_rawDescOnce sync.Once
	file_scrcpy_proto_rawDescData []byte
)

func file_scrcpy_proto_rawDescGZIP() []byte {
	file_scrcpy_proto_rawDescOnce.Do(func() {
		file_scrcpy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scrcpy_proto_rawDesc), len(file_scrcpy_proto_rawDesc)))
	})
	return file_scrcpy_proto_rawDescData
}

var file_scrcpy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scrcpy_proto_goTypes = []any{
	(*Empty)(nil),           // 0: Empty
	(*ParamValue)(nil),      // 1: ParamValue
	(*ReplyMessage)(nil),    // 2: ReplyMessage
	(*ReplyEndMessage)(nil), // 3: ReplyEndMessage
	nil,                     // 4: ReplyMessage.PayloadEntry
}
var file_scrcpy_proto_depIdxs = []int32{
	4, // 0: ReplyMessage.payload:type_name -> ReplyMessage.PayloadEntry
	1, // 1: ReplyMessage.PayloadEntry.value:type_name -> ParamValue
	0, // 2: ScrcpyService.onStart:input_type -> Empty
	0, // 3: ScrcpyService.onEnd:input_type -> Empty
	0, // 4: ScrcpyService.onRequestIDRFrame:input_type -> Empty
	2, // 5: ScrcpyService.onStart:output_type -> ReplyMessage
	3, // 6: ScrcpyService.onEnd:output_type -> ReplyEndMessage
	3, // 7: ScrcpyService.onRequestIDRFrame:output_type -> ReplyEndMessage
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scrcpy_proto_init() }
func file_scrcpy_proto_init() {
	if File_scrcpy_proto != nil {
		return
	}
	file_scrcpy_proto_msgTypes[1].OneofWrappers = []any{
		(*ParamValue_ValInt)(nil),
		(*ParamValue_ValDouble)(nil),
		(*ParamValue_ValString)(nil),
		(*ParamValue_ValBool)(nil),
		(*ParamValue_ValBytes)(nil),
		(*ParamValue_ValFloat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scrcpy_proto_rawDesc), len(file_scrcpy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scrcpy_proto_goTypes,
		DependencyIndexes: file_scrcpy_proto_depIdxs,
		MessageInfos:      file_scrcpy_proto_msgTypes,
	}.Build()
	File_scrcpy_proto = out.File
	file_scrcpy_proto_goTypes = nil
	file_scrcpy_proto_depIdxs = nil
}
