// Code generated by generate:cienv task. DO NOT EDIT.
// Built from `.env.ci` at package/build time; open-source default is empty.
package backend

// embeddedCIEnv holds private CI defaults baked into the binary at build time.
// Runtime process env and a local `.env.ci` (dev) still take precedence when set.
var embeddedCIEnv = map[string]string{
	"POSTHOG_API_KEY"      : "phc_CFPbJUBCcGtAjNFp86qzGBZtaDv7Dif9iz4KVramREBa",
	"POSTHOG_CAPTURE_URL"  : "https://us.i.posthog.com/capture/",
	"VITE_POSTHOG_KEY"     : "phc_CFPbJUBCcGtAjNFp86qzGBZtaDv7Dif9iz4KVramREBa",
	"VITE_POSTHOG_HOST"    : "https://us.i.posthog.com",
	"VITE_UPDATE_CHECK_URL": "https://raw.githubusercontent.com/Joehaivo/Joehaivo.github.io/refs/heads/main/HadiceVersion.json",
	"VITE_DOCS_URL"        : "https://huolala.feishu.cn/wiki/We5pwcpP0ivQAck51esclHOtnSf",
}
