// Code generated by generate:cienv task. DO NOT EDIT.
// Built from `.env.ci` at package/build time; open-source default is empty.
package backend

// embeddedCIEnv holds private CI defaults baked into the binary at build time.
// Runtime process env and a local `.env.ci` (dev) still take precedence when set.
var embeddedCIEnv = map[string]string{
	"POSTHOG_API_KEY"      : "",
	"POSTHOG_CAPTURE_URL"  : "",
	"VITE_POSTHOG_KEY"     : "",
	"VITE_POSTHOG_HOST"    : "",
	"VITE_UPDATE_CHECK_URL": "",
	"VITE_DOCS_URL"        : "",
}
