// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {hdc} from '../models';
import {phoneAgent} from '../models';

export function CheckPortForwardStatus(arg1:number,arg2:number):Promise<backend.PortForwardStatus>;

export function CheckReversePortForwardStatus(arg1:string,arg2:number,arg3:number):Promise<backend.PortForwardStatus>;

export function CheckServer():Promise<Record<string, string>>;

export function CheckUpdate(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ClearAppCache(arg1:string,arg2:string):Promise<hdc.HdcResult>;

export function ClearAppData(arg1:string,arg2:string):Promise<hdc.HdcResult>;

export function ClearRequests(arg1:string):Promise<void>;

export function ClearScreenshotHistory(arg1:string):Promise<hdc.HdcResult>;

export function Click(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function ConfigurePortForward(arg1:string,arg2:number,arg3:number,arg4:string):Promise<backend.PortForwardStatus>;

export function ConnectDevice(arg1:string):Promise<hdc.HdcResult>;

export function CopyFilePathToClipboard(arg1:string):Promise<hdc.HdcResult>;

export function CopyImageToClipboard(arg1:string):Promise<hdc.HdcResult>;

export function CopyScreenRecordFileToTmp(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function DebugGetServerInfo():Promise<Record<string, any>>;

export function DeleteDeviceFile(arg1:string,arg2:string):Promise<hdc.HdcResult>;

export function DeleteLocalFile(arg1:string):Promise<hdc.HdcResult>;

export function DeleteScreenshot(arg1:string):Promise<hdc.HdcResult>;

export function DisconnectDevice(arg1:string):Promise<hdc.HdcResult>;

export function DownloadScreenRecordFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ExecuteHdc(arg1:Array<string>):Promise<hdc.HdcResult>;

export function ExecuteHdcCommand(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ExecutePhoneAgentStep(arg1:string,arg2:string,arg3:boolean):Promise<Record<string, any>>;

export function ExtractVideoFirstFrame(arg1:string):Promise<string>;

export function GetAppFullDetail(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetAppList(arg1:string,arg2:string,arg3:boolean):Promise<hdc.AppListResult>;

export function GetAppRunningRecords(arg1:string):Promise<Array<Record<string, any>>>;

export function GetAppShortcuts(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetAppVersion():Promise<string>;

export function GetBatteryInfo(arg1:string):Promise<hdc.BatteryInfo>;

export function GetCaptureServerStatus(arg1:string):Promise<Record<string, any>>;

export function GetCaptureStatus(arg1:string):Promise<Record<string, any>>;

export function GetCpuDetailInfo(arg1:string):Promise<hdc.CpuDetailInfo>;

export function GetCpuUsageInfo(arg1:string):Promise<hdc.CpuUsageInfo>;

export function GetDefaultScreenshotPath():Promise<string>;

export function GetDeviceDetailInfo(arg1:string):Promise<hdc.DeviceDetailInfo>;

export function GetDeviceInfo(arg1:string):Promise<hdc.DeviceInfo>;

export function GetDeviceProperty(arg1:string,arg2:string):Promise<string>;

export function GetDeviceUdid(arg1:string):Promise<string>;

export function GetDisplaySize(arg1:string):Promise<backend.DisplaySize>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetGraphicsInfo(arg1:string):Promise<hdc.GraphicsInfo>;

export function GetHdcDebugInfo():Promise<Record<string, string>>;

export function GetHdcVersion():Promise<string>;

export function GetLogFilePath():Promise<string>;

export function GetMemoryDetailInfo(arg1:string):Promise<hdc.MemoryDetailInfo>;

export function GetMemoryInfo(arg1:string):Promise<hdc.MemoryInfo>;

export function GetMissionList(arg1:string):Promise<Array<Record<string, any>>>;

export function GetNetworkInfo(arg1:string):Promise<Array<hdc.NetworkInfo>>;

export function GetNetworkTrafficInfo(arg1:string):Promise<Array<hdc.NetworkTrafficInfo>>;

export function GetOnlineAppInfo(arg1:string):Promise<hdc.OnlineAppInfo>;

export function GetPhoneAgentStatus(arg1:string):Promise<Record<string, any>>;

export function GetProcessDetail(arg1:string,arg2:number):Promise<Record<string, string>>;

export function GetProcessList(arg1:string,arg2:string):Promise<hdc.ProcessListResult>;

export function GetProcessListAsync(arg1:string,arg2:string):Promise<void>;

export function GetRequests(arg1:string,arg2:number):Promise<Array<backend.NetworkRequest>>;

export function GetScreenRecordHistory(arg1:string):Promise<Array<Record<string, any>>>;

export function GetScreenshotHistory(arg1:string):Promise<Array<Record<string, any>>>;

export function GetStorageInfo(arg1:string):Promise<hdc.StorageInfo>;

export function GetSystemProperties(arg1:string):Promise<hdc.SystemProperties>;

export function GetSystemRuntime(arg1:string):Promise<hdc.SystemRuntime>;

export function GetUptimeInfo(arg1:string):Promise<Record<string, any>>;

export function GetUserDocumentsDirectory():Promise<string>;

export function GetUserDownloadsDirectory():Promise<string>;

export function GetUserHomeDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallApp(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<hdc.HdcResult>;

export function KillProcess(arg1:string,arg2:number,arg3:boolean):Promise<hdc.HdcResult>;

export function ForceStopApp(arg1:string,arg2:string):Promise<hdc.HdcResult>;

export function KillServer():Promise<hdc.HdcResult>;

export function ListDeviceDirectory(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ListDevices(arg1:boolean):Promise<Array<hdc.HdcDevice>>;

export function ListDevicesWithInfo():Promise<Array<hdc.HdcDevice>>;

export function ListLocalDirectory(arg1:string):Promise<Record<string, any>>;

export function ListPortForwards():Promise<Array<backend.PortForwardItem>>;

export function OpenBrowser(arg1:string):Promise<void>;

export function OpenFileInSystem(arg1:string):Promise<hdc.HdcResult>;

export function OpenFolder(arg1:string):Promise<hdc.HdcResult>;

export function OpenLogFile(arg1:string):Promise<Record<string, any>>;

export function OpenScreenshotFile(arg1:string):Promise<hdc.HdcResult>;

export function OpenScreenshotFolder(arg1:string):Promise<hdc.HdcResult>;

export function ParseHapAppInfo(arg1:string):Promise<hdc.HapAppInfo>;

export function PressBack(arg1:string):Promise<Record<string, any>>;

export function PressHome(arg1:string):Promise<Record<string, any>>;

export function PressKey(arg1:string,arg2:number):Promise<Record<string, any>>;

export function PullFileFromDevice(arg1:string,arg2:string,arg3:string):Promise<hdc.HdcResult>;

export function PushFileToDevice(arg1:string,arg2:string,arg3:string):Promise<hdc.HdcResult>;

export function PushMockConfigToClient(arg1:string,arg2:string):Promise<void>;

export function QueryScreenRecordFile(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Record<string, any>>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function RemovePortForward(arg1:number,arg2:number):Promise<hdc.HdcResult>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartServer():Promise<hdc.HdcResult>;

export function SaveLogsToFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SelectHapFile():Promise<string>;

export function SelectScreenshotPath():Promise<string>;

export function StartApp(arg1:string,arg2:string):Promise<hdc.HdcResult>;

export function StartCapture(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function StartCaptureServer(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function StartHilogStream(arg1:string,arg2:Record<string, any>):Promise<hdc.HdcResult>;

export function StartPhoneAgent(arg1:phoneAgent.AgentConfig):Promise<Record<string, any>>;

export function StartScreenMirror(arg1:string,arg2:number):Promise<Record<string, any>>;

export function StartScreenRecord(arg1:string):Promise<Record<string, any>>;

export function StartServer():Promise<hdc.HdcResult>;

export function StartShell(arg1:string):Promise<boolean>;

export function StopAllHilogStreams():Promise<hdc.HdcResult>;

export function StopAllShells():Promise<void>;

export function StopApp(arg1:string,arg2:string):Promise<hdc.HdcResult>;

export function StopCapture(arg1:string):Promise<void>;

export function StopCapturePort(arg1:string,arg2:number):Promise<void>;

export function StopCaptureServer(arg1:string):Promise<void>;

export function StopHilogStream(arg1:string):Promise<hdc.HdcResult>;

export function StopPhoneAgent(arg1:string):Promise<Record<string, any>>;

export function StopScreenMirror(arg1:string):Promise<Record<string, any>>;

export function StopScreenRecord(arg1:string):Promise<hdc.HdcResult>;

export function StopShell(arg1:string):Promise<void>;

export function TakeScreenshot(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function TestConnection(arg1:number):Promise<Record<string, any>>;

export function TouchDown(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function TouchMove(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function TouchMoveFromTo(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<Record<string, any>>;

export function TouchUp(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function UninstallApp(arg1:string,arg2:string):Promise<hdc.HdcResult>;

export function WaitForDevice(arg1:string):Promise<hdc.HdcResult>;

export function WriteToShell(arg1:string,arg2:string):Promise<void>;
