// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPortForwardStatus(arg1, arg2) {
  return window['go']['backend']['App']['CheckPortForwardStatus'](arg1, arg2);
}

export function CheckReversePortForwardStatus(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CheckReversePortForwardStatus'](arg1, arg2, arg3);
}

export function CheckServer() {
  return window['go']['backend']['App']['CheckServer']();
}

export function CheckUpdate(arg1, arg2) {
  return window['go']['backend']['App']['CheckUpdate'](arg1, arg2);
}

export function ClearAppCache(arg1, arg2) {
  return window['go']['backend']['App']['ClearAppCache'](arg1, arg2);
}

export function ClearAppData(arg1, arg2) {
  return window['go']['backend']['App']['ClearAppData'](arg1, arg2);
}

export function ClearRequests(arg1) {
  return window['go']['backend']['App']['ClearRequests'](arg1);
}

export function ClearScreenshotHistory(arg1) {
  return window['go']['backend']['App']['ClearScreenshotHistory'](arg1);
}

export function Click(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Click'](arg1, arg2, arg3);
}

export function ConfigurePortForward(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ConfigurePortForward'](arg1, arg2, arg3, arg4);
}

export function ConnectDevice(arg1) {
  return window['go']['backend']['App']['ConnectDevice'](arg1);
}

export function CopyFilePathToClipboard(arg1) {
  return window['go']['backend']['App']['CopyFilePathToClipboard'](arg1);
}

export function CopyImageToClipboard(arg1) {
  return window['go']['backend']['App']['CopyImageToClipboard'](arg1);
}

export function CopyScreenRecordFileToTmp(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CopyScreenRecordFileToTmp'](arg1, arg2, arg3, arg4);
}

export function DebugGetServerInfo() {
  return window['go']['backend']['App']['DebugGetServerInfo']();
}

export function DeleteDeviceFile(arg1, arg2) {
  return window['go']['backend']['App']['DeleteDeviceFile'](arg1, arg2);
}

export function DeleteLocalFile(arg1) {
  return window['go']['backend']['App']['DeleteLocalFile'](arg1);
}

export function DeleteScreenshot(arg1) {
  return window['go']['backend']['App']['DeleteScreenshot'](arg1);
}

export function DisconnectDevice(arg1) {
  return window['go']['backend']['App']['DisconnectDevice'](arg1);
}

export function DownloadScreenRecordFile(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['DownloadScreenRecordFile'](arg1, arg2, arg3, arg4);
}

export function ExecuteHdc(arg1) {
  return window['go']['backend']['App']['ExecuteHdc'](arg1);
}

export function ExecuteHdcCommand(arg1, arg2) {
  return window['go']['backend']['App']['ExecuteHdcCommand'](arg1, arg2);
}

export function ExecutePhoneAgentStep(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ExecutePhoneAgentStep'](arg1, arg2, arg3);
}

export function ExtractVideoFirstFrame(arg1) {
  return window['go']['backend']['App']['ExtractVideoFirstFrame'](arg1);
}

export function GetAppFullDetail(arg1, arg2) {
  return window['go']['backend']['App']['GetAppFullDetail'](arg1, arg2);
}

export function GetAppList(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetAppList'](arg1, arg2, arg3);
}

export function GetAppRunningRecords(arg1) {
  return window['go']['backend']['App']['GetAppRunningRecords'](arg1);
}

export function GetAppShortcuts(arg1, arg2) {
  return window['go']['backend']['App']['GetAppShortcuts'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['backend']['App']['GetAppVersion']();
}

export function GetBatteryInfo(arg1) {
  return window['go']['backend']['App']['GetBatteryInfo'](arg1);
}

export function GetCaptureServerStatus(arg1) {
  return window['go']['backend']['App']['GetCaptureServerStatus'](arg1);
}

export function GetCaptureStatus(arg1) {
  return window['go']['backend']['App']['GetCaptureStatus'](arg1);
}

export function GetCpuDetailInfo(arg1) {
  return window['go']['backend']['App']['GetCpuDetailInfo'](arg1);
}

export function GetCpuUsageInfo(arg1) {
  return window['go']['backend']['App']['GetCpuUsageInfo'](arg1);
}

export function GetDefaultScreenshotPath() {
  return window['go']['backend']['App']['GetDefaultScreenshotPath']();
}

export function GetDeviceDetailInfo(arg1) {
  return window['go']['backend']['App']['GetDeviceDetailInfo'](arg1);
}

export function GetDeviceInfo(arg1) {
  return window['go']['backend']['App']['GetDeviceInfo'](arg1);
}

export function GetDeviceProperty(arg1, arg2) {
  return window['go']['backend']['App']['GetDeviceProperty'](arg1, arg2);
}

export function GetDeviceUdid(arg1) {
  return window['go']['backend']['App']['GetDeviceUdid'](arg1);
}

export function GetDisplaySize(arg1) {
  return window['go']['backend']['App']['GetDisplaySize'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['backend']['App']['GetFileInfo'](arg1);
}

export function GetGraphicsInfo(arg1) {
  return window['go']['backend']['App']['GetGraphicsInfo'](arg1);
}

export function GetHdcDebugInfo() {
  return window['go']['backend']['App']['GetHdcDebugInfo']();
}

export function GetHdcVersion() {
  return window['go']['backend']['App']['GetHdcVersion']();
}

export function GetLogFilePath() {
  return window['go']['backend']['App']['GetLogFilePath']();
}

export function GetMemoryDetailInfo(arg1) {
  return window['go']['backend']['App']['GetMemoryDetailInfo'](arg1);
}

export function GetMemoryInfo(arg1) {
  return window['go']['backend']['App']['GetMemoryInfo'](arg1);
}

export function GetMissionList(arg1) {
  return window['go']['backend']['App']['GetMissionList'](arg1);
}

export function GetNetworkInfo(arg1) {
  return window['go']['backend']['App']['GetNetworkInfo'](arg1);
}

export function GetNetworkTrafficInfo(arg1) {
  return window['go']['backend']['App']['GetNetworkTrafficInfo'](arg1);
}

export function GetOnlineAppInfo(arg1) {
  return window['go']['backend']['App']['GetOnlineAppInfo'](arg1);
}

export function GetPhoneAgentStatus(arg1) {
  return window['go']['backend']['App']['GetPhoneAgentStatus'](arg1);
}

export function GetProcessDetail(arg1, arg2) {
  return window['go']['backend']['App']['GetProcessDetail'](arg1, arg2);
}

export function GetProcessList(arg1, arg2) {
  return window['go']['backend']['App']['GetProcessList'](arg1, arg2);
}

export function GetProcessListAsync(arg1, arg2) {
  return window['go']['backend']['App']['GetProcessListAsync'](arg1, arg2);
}

export function GetRequests(arg1, arg2) {
  return window['go']['backend']['App']['GetRequests'](arg1, arg2);
}

export function GetScreenRecordHistory(arg1) {
  return window['go']['backend']['App']['GetScreenRecordHistory'](arg1);
}

export function GetScreenshotHistory(arg1) {
  return window['go']['backend']['App']['GetScreenshotHistory'](arg1);
}

export function GetStorageInfo(arg1) {
  return window['go']['backend']['App']['GetStorageInfo'](arg1);
}

export function GetSystemProperties(arg1) {
  return window['go']['backend']['App']['GetSystemProperties'](arg1);
}

export function GetSystemRuntime(arg1) {
  return window['go']['backend']['App']['GetSystemRuntime'](arg1);
}

export function GetUptimeInfo(arg1) {
  return window['go']['backend']['App']['GetUptimeInfo'](arg1);
}

export function GetUserDocumentsDirectory() {
  return window['go']['backend']['App']['GetUserDocumentsDirectory']();
}

export function GetUserDownloadsDirectory() {
  return window['go']['backend']['App']['GetUserDownloadsDirectory']();
}

export function GetUserHomeDirectory() {
  return window['go']['backend']['App']['GetUserHomeDirectory']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function InstallApp(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['InstallApp'](arg1, arg2, arg3, arg4);
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['backend']['App']['KillProcess'](arg1, arg2, arg3);
}

export function ForceStopApp(arg1, arg2) {
  return window['go']['backend']['App']['ForceStopApp'](arg1, arg2);
}

export function KillServer() {
  return window['go']['backend']['App']['KillServer']();
}

export function ListDeviceDirectory(arg1, arg2) {
  return window['go']['backend']['App']['ListDeviceDirectory'](arg1, arg2);
}

export function ListDevices(arg1) {
  return window['go']['backend']['App']['ListDevices'](arg1);
}

export function ListDevicesWithInfo() {
  return window['go']['backend']['App']['ListDevicesWithInfo']();
}

export function ListLocalDirectory(arg1) {
  return window['go']['backend']['App']['ListLocalDirectory'](arg1);
}

export function ListPortForwards() {
  return window['go']['backend']['App']['ListPortForwards']();
}

export function OpenBrowser(arg1) {
  return window['go']['backend']['App']['OpenBrowser'](arg1);
}

export function OpenFileInSystem(arg1) {
  return window['go']['backend']['App']['OpenFileInSystem'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['backend']['App']['OpenFolder'](arg1);
}

export function OpenLogFile(arg1) {
  return window['go']['backend']['App']['OpenLogFile'](arg1);
}

export function OpenScreenshotFile(arg1) {
  return window['go']['backend']['App']['OpenScreenshotFile'](arg1);
}

export function OpenScreenshotFolder(arg1) {
  return window['go']['backend']['App']['OpenScreenshotFolder'](arg1);
}

export function ParseHapAppInfo(arg1) {
  return window['go']['backend']['App']['ParseHapAppInfo'](arg1);
}

export function PressBack(arg1) {
  return window['go']['backend']['App']['PressBack'](arg1);
}

export function PressHome(arg1) {
  return window['go']['backend']['App']['PressHome'](arg1);
}

export function PressKey(arg1, arg2) {
  return window['go']['backend']['App']['PressKey'](arg1, arg2);
}

export function PullFileFromDevice(arg1, arg2, arg3) {
  return window['go']['backend']['App']['PullFileFromDevice'](arg1, arg2, arg3);
}

export function PushFileToDevice(arg1, arg2, arg3) {
  return window['go']['backend']['App']['PushFileToDevice'](arg1, arg2, arg3);
}

export function PushMockConfigToClient(arg1, arg2) {
  return window['go']['backend']['App']['PushMockConfigToClient'](arg1, arg2);
}

export function QueryScreenRecordFile(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['QueryScreenRecordFile'](arg1, arg2, arg3, arg4);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['backend']['App']['ReadImageAsBase64'](arg1);
}

export function RemovePortForward(arg1, arg2) {
  return window['go']['backend']['App']['RemovePortForward'](arg1, arg2);
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function RestartServer() {
  return window['go']['backend']['App']['RestartServer']();
}

export function SaveLogsToFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveLogsToFile'](arg1, arg2);
}

export function SelectHapFile() {
  return window['go']['backend']['App']['SelectHapFile']();
}

export function SelectScreenshotPath() {
  return window['go']['backend']['App']['SelectScreenshotPath']();
}

export function StartApp(arg1, arg2) {
  return window['go']['backend']['App']['StartApp'](arg1, arg2);
}

export function StartCapture(arg1, arg2, arg3) {
  return window['go']['backend']['App']['StartCapture'](arg1, arg2, arg3);
}

export function StartCaptureServer(arg1, arg2, arg3) {
  return window['go']['backend']['App']['StartCaptureServer'](arg1, arg2, arg3);
}

export function StartHilogStream(arg1, arg2) {
  return window['go']['backend']['App']['StartHilogStream'](arg1, arg2);
}

export function StartPhoneAgent(arg1) {
  return window['go']['backend']['App']['StartPhoneAgent'](arg1);
}

export function StartScreenMirror(arg1, arg2) {
  return window['go']['backend']['App']['StartScreenMirror'](arg1, arg2);
}

export function StartScreenRecord(arg1) {
  return window['go']['backend']['App']['StartScreenRecord'](arg1);
}

export function StartServer() {
  return window['go']['backend']['App']['StartServer']();
}

export function StartShell(arg1) {
  return window['go']['backend']['App']['StartShell'](arg1);
}

export function StopAllHilogStreams() {
  return window['go']['backend']['App']['StopAllHilogStreams']();
}

export function StopAllShells() {
  return window['go']['backend']['App']['StopAllShells']();
}

export function StopApp(arg1, arg2) {
  return window['go']['backend']['App']['StopApp'](arg1, arg2);
}

export function StopCapture(arg1) {
  return window['go']['backend']['App']['StopCapture'](arg1);
}

export function StopCapturePort(arg1, arg2) {
  return window['go']['backend']['App']['StopCapturePort'](arg1, arg2);
}

export function StopCaptureServer(arg1) {
  return window['go']['backend']['App']['StopCaptureServer'](arg1);
}

export function StopHilogStream(arg1) {
  return window['go']['backend']['App']['StopHilogStream'](arg1);
}

export function StopPhoneAgent(arg1) {
  return window['go']['backend']['App']['StopPhoneAgent'](arg1);
}

export function StopScreenMirror(arg1) {
  return window['go']['backend']['App']['StopScreenMirror'](arg1);
}

export function StopScreenRecord(arg1) {
  return window['go']['backend']['App']['StopScreenRecord'](arg1);
}

export function StopShell(arg1) {
  return window['go']['backend']['App']['StopShell'](arg1);
}

export function TakeScreenshot(arg1, arg2, arg3) {
  return window['go']['backend']['App']['TakeScreenshot'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}

export function TouchDown(arg1, arg2, arg3) {
  return window['go']['backend']['App']['TouchDown'](arg1, arg2, arg3);
}

export function TouchMove(arg1, arg2, arg3) {
  return window['go']['backend']['App']['TouchMove'](arg1, arg2, arg3);
}

export function TouchMoveFromTo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['TouchMoveFromTo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TouchUp(arg1, arg2, arg3) {
  return window['go']['backend']['App']['TouchUp'](arg1, arg2, arg3);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['backend']['App']['UninstallApp'](arg1, arg2);
}

export function WaitForDevice(arg1) {
  return window['go']['backend']['App']['WaitForDevice'](arg1);
}

export function WriteToShell(arg1, arg2) {
  return window['go']['backend']['App']['WriteToShell'](arg1, arg2);
}
