// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AdbResult 表示 ADB 命令执行结果
 */
export class AdbResult {
    /**
     * Creates a new AdbResult instance.
     * @param {Partial<AdbResult>} [$$source = {}] - The source object to create the AdbResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdbResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AdbResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdbResult(/** @type {Partial<AdbResult>} */($$parsedSource));
    }
}
