// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AdbResult 表示 ADB 命令执行结果
 */
export class AdbResult {
    /**
     * Creates a new AdbResult instance.
     * @param {Partial<AdbResult>} [$$source = {}] - The source object to create the AdbResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AdbResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AdbResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AdbResult(/** @type {Partial<AdbResult>} */($$parsedSource));
    }
}

/**
 * AndroidAppInfo 简化的安卓应用信息（用于日志页面等场景）
 */
export class AndroidAppInfo {
    /**
     * Creates a new AndroidAppInfo instance.
     * @param {Partial<AndroidAppInfo>} [$$source = {}] - The source object to create the AndroidAppInfo.
     */
    constructor($$source = {}) {
        if (!("packageName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packageName"] = "";
        }
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("isSystemApp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSystemApp"] = false;
        }
        if (!("isRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRunning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AndroidAppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AndroidAppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AndroidAppInfo(/** @type {Partial<AndroidAppInfo>} */($$parsedSource));
    }
}

/**
 * AndroidAppListResult 简化的安卓应用列表结果
 */
export class AndroidAppListResult {
    /**
     * Creates a new AndroidAppListResult instance.
     * @param {Partial<AndroidAppListResult>} [$$source = {}] - The source object to create the AndroidAppListResult.
     */
    constructor($$source = {}) {
        if (!("apps" in $$source)) {
            /**
             * @member
             * @type {AndroidAppInfo[]}
             */
            this["apps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AndroidAppListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AndroidAppListResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apps" in $$parsedSource) {
            $$parsedSource["apps"] = $$createField0_0($$parsedSource["apps"]);
        }
        return new AndroidAppListResult(/** @type {Partial<AndroidAppListResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AndroidAppInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
