// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是 v3 中的服务，提供所有应用功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as adb$0 from "./adb/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "./device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hdc$0 from "./hdc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as phoneAgent$0 from "./phoneAgent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AdbConnectDevice TCP 连接安卓设备
 * @param {string} ipPort
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbConnectDevice(ipPort) {
    return $Call.ByID(2466082099, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AdbDisconnectDevice 断开安卓设备连接
 * @param {string} ipPort
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbDisconnectDevice(ipPort) {
    return $Call.ByID(248434445, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AdbKillServer 终止 ADB 服务
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbKillServer() {
    return $Call.ByID(1771322770).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AdbStartServer 启动 ADB 服务
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbStartServer() {
    return $Call.ByID(1552469824).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckPortForwardStatus 检查端口转发状态
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<$models.PortForwardStatus | null>}
 */
export function CheckPortForwardStatus(localPort, devicePort) {
    return $Call.ByID(2791344550, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckReversePortForwardStatus 检查反向端口转发状态
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<$models.PortForwardStatus | null>}
 */
export function CheckReversePortForwardStatus(deviceId, localPort, devicePort) {
    return $Call.ByID(1466833148, deviceId, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckServer 检查服务状态
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function CheckServer() {
    return $Call.ByID(3182240807).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * CheckUpdate 检查更新
 * updateCheckURL: 更新检查JSON的URL地址
 * currentVersion: 当前软件版本号
 * @param {string} updateCheckURL
 * @param {string} currentVersion
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function CheckUpdate(updateCheckURL, currentVersion) {
    return $Call.ByID(1722630213, updateCheckURL, currentVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClearAppCache 清除应用缓存
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ClearAppCache(connectKey, packageName) {
    return $Call.ByID(2869385210, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ClearAppData 清除应用数据
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ClearAppData(connectKey, packageName) {
    return $Call.ByID(1098465608, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ClearAppDiskCache 清除应用磁盘缓存
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ClearAppDiskCache() {
    return $Call.ByID(4067881341).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClearRequests 清空请求列表（清空该设备所有端口的请求）
 * @param {string} deviceId
 * @returns {$CancellablePromise<void>}
 */
export function ClearRequests(deviceId) {
    return $Call.ByID(3093017343, deviceId);
}

/**
 * ClearScreenshotHistory 清空截图历史
 * @param {string} savePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ClearScreenshotHistory(savePath) {
    return $Call.ByID(1263868191, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Click 点击事件（使用 uitest uiInput click）
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function Click(deviceSn, x, y) {
    return $Call.ByID(3956854692, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClosePanelWindow 关闭指定菜单的独立窗口
 * 若窗口存在则关闭并返回 true，否则返回 false
 * @param {string} menuId
 * @returns {$CancellablePromise<boolean>}
 */
export function ClosePanelWindow(menuId) {
    return $Call.ByID(4000925250, menuId);
}

/**
 * ConfigurePortForward 配置端口转发
 * type参数: "Forward" 使用 fport 命令, "Reverse" 使用 rport 命令
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @param {string} portType
 * @returns {$CancellablePromise<$models.PortForwardStatus | null>}
 */
export function ConfigurePortForward(deviceId, localPort, devicePort, portType) {
    return $Call.ByID(2429748248, deviceId, localPort, devicePort, portType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ConnectDevice TCP 连接设备
 * ipPort: IP地址和端口，格式如 "192.168.1.100:8710"
 * @param {string} ipPort
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ConnectDevice(ipPort) {
    return $Call.ByID(3760035236, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * CopyFilePathToClipboard 复制文件路径到剪贴板（Finder 风格）
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function CopyFilePathToClipboard(filePath) {
    return $Call.ByID(3251974405, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * CopyImageToClipboard 复制图片到剪贴板
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function CopyImageToClipboard(filePath) {
    return $Call.ByID(3684044035, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * CopyScreenRecordFileToTmp 将录屏文件复制到临时目录
 * @param {string} connectKey
 * @param {string} uri
 * @param {string} originalPath
 * @param {string} fileName
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function CopyScreenRecordFileToTmp(connectKey, uri, originalPath, fileName) {
    return $Call.ByID(304126924, connectKey, uri, originalPath, fileName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DebugGetServerInfo 用于调试：获取服务器状态信息
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function DebugGetServerInfo() {
    return $Call.ByID(1493590458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DeleteDeviceFile 删除设备上的文件
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} filePath
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DeleteDeviceFile(connectKey, filePath, platform) {
    return $Call.ByID(4135707339, connectKey, filePath, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DeleteLocalFile 删除本地文件
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DeleteLocalFile(filePath) {
    return $Call.ByID(36165664, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DeleteScreenshot 删除截图文件
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DeleteScreenshot(filePath) {
    return $Call.ByID(2869236011, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DisconnectDevice 断开 TCP 连接
 * ipPort: IP地址和端口
 * @param {string} ipPort
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DisconnectDevice(ipPort) {
    return $Call.ByID(296369880, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DownloadScreenRecordFile 下载录屏文件到本地
 * @param {string} connectKey
 * @param {string} devicePath
 * @param {string} savePath
 * @param {string} fileName
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function DownloadScreenRecordFile(connectKey, devicePath, savePath, fileName) {
    return $Call.ByID(4207764675, connectKey, devicePath, savePath, fileName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ExecuteAdb 执行任意 ADB 命令
 * @param {string[]} args
 * @returns {$CancellablePromise<adb$0.AdbResult | null>}
 */
export function ExecuteAdb(args) {
    return $Call.ByID(4047443204, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ExecuteHdc 执行任意 HDC 命令
 * args: HDC 命令参数数组
 * @param {string[]} args
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ExecuteHdc(args) {
    return $Call.ByID(3892524588, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ExecuteHdcCommand 执行 HDC 命令
 * @param {string} connectKey
 * @param {string} shellCommand
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ExecuteHdcCommand(connectKey, shellCommand) {
    return $Call.ByID(949240709, connectKey, shellCommand).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ExecutePhoneAgentStep 执行Agent单步操作
 * sessionID: 会话ID
 * task: 任务描述（仅在第一步需要）
 * isFirst: 是否是第一步
 * 返回执行结果
 * @param {string} sessionID
 * @param {string} task
 * @param {boolean} isFirst
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ExecutePhoneAgentStep(sessionID, task, isFirst) {
    return $Call.ByID(266848336, sessionID, task, isFirst).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ExtractVideoFirstFrame 提取视频第一帧并返回 base64 图片数据
 * @param {string} videoPath
 * @returns {$CancellablePromise<string>}
 */
export function ExtractVideoFirstFrame(videoPath) {
    return $Call.ByID(1962286667, videoPath);
}

/**
 * ForceStopApp 使用 aa force-stop 命令停止应用
 * connectKey: 设备标识
 * packageName: 应用包名
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ForceStopApp(connectKey, packageName) {
    return $Call.ByID(1571092034, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetAdbDebugInfo 获取 ADB 调试信息
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetAdbDebugInfo() {
    return $Call.ByID(482953372).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAdbVersion 获取 ADB 版本
 * @returns {$CancellablePromise<string>}
 */
export function GetAdbVersion() {
    return $Call.ByID(1737933583);
}

/**
 * GetAppFullDetail 获取应用完整详情（包括权限和能力信息）
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetAppFullDetail(connectKey, packageName) {
    return $Call.ByID(101827007, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAppList 获取应用列表
 * incremental: 是否使用渐进式加载（先返回基本列表，然后通过事件推送详情）
 * @param {string} connectKey
 * @param {string} filter
 * @param {boolean} incremental
 * @returns {$CancellablePromise<hdc$0.AppListResult | null>}
 */
export function GetAppList(connectKey, filter, incremental) {
    return $Call.ByID(3855091419, connectKey, filter, incremental).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetAppRunningRecords 获取运行中的应用记录
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetAppRunningRecords(connectKey) {
    return $Call.ByID(1410444220, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetAppShortcuts 获取应用快捷方式
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetAppShortcuts(connectKey, packageName) {
    return $Call.ByID(1555440534, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetAppVersion returns the current application version
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(107599277);
}

/**
 * GetBatteryInfo 获取电池信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.BatteryInfo | null>}
 */
export function GetBatteryInfo(connectKey) {
    return $Call.ByID(915172645, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetCachedAppIcon 获取磁盘缓存的应用图标（base64格式）
 * @param {string} packageName
 * @returns {$CancellablePromise<string>}
 */
export function GetCachedAppIcon(packageName) {
    return $Call.ByID(2441737676, packageName);
}

/**
 * GetCachedAppList 获取磁盘缓存的应用列表
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetCachedAppList() {
    return $Call.ByID(1030082541).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCaptureServerStatus 获取新架构抓包状态
 * @param {string} deviceId
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetCaptureServerStatus(deviceId) {
    return $Call.ByID(368612711, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCaptureStatus 获取抓包状态（返回该设备所有端口的状态）
 * @param {string} deviceId
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetCaptureStatus(deviceId) {
    return $Call.ByID(267573140, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCpuDetailInfo 获取详细 CPU 使用信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.CpuDetailInfo | null>}
 */
export function GetCpuDetailInfo(connectKey) {
    return $Call.ByID(4024315367, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetCpuUsageInfo 获取 CPU 使用信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.CpuUsageInfo | null>}
 */
export function GetCpuUsageInfo(connectKey) {
    return $Call.ByID(1978934221, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetDefaultScreenshotPath 获取默认截图路径
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultScreenshotPath() {
    return $Call.ByID(713032378);
}

/**
 * GetDeviceDetailInfo 获取设备完整详细信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.DeviceDetailInfo | null>}
 */
export function GetDeviceDetailInfo(connectKey) {
    return $Call.ByID(4192428503, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetDeviceInfo 获取设备基本信息（产品名称和型号）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.DeviceInfo | null>}
 */
export function GetDeviceInfo(connectKey) {
    return $Call.ByID(1134836266, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetDeviceProperty 获取设备属性
 * connectKey: 设备标识符
 * property: 属性名，如 const.product.name
 * @param {string} connectKey
 * @param {string} property
 * @returns {$CancellablePromise<string>}
 */
export function GetDeviceProperty(connectKey, property) {
    return $Call.ByID(171330791, connectKey, property);
}

/**
 * GetDeviceUdid 获取设备UDID
 * @param {string} connectKey
 * @returns {$CancellablePromise<string>}
 */
export function GetDeviceUdid(connectKey) {
    return $Call.ByID(420197950, connectKey);
}

/**
 * GetDisplaySize 获取屏幕尺寸
 * @param {string} deviceSn
 * @returns {$CancellablePromise<$models.DisplaySize | null>}
 */
export function GetDisplaySize(deviceSn) {
    return $Call.ByID(1578220167, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetFileInfo 获取文件信息
 * @param {string} filePath
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetFileInfo(filePath) {
    return $Call.ByID(856762190, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetGraphicsInfo 获取图形性能信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.GraphicsInfo | null>}
 */
export function GetGraphicsInfo(connectKey) {
    return $Call.ByID(557112341, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * GetHdcDebugInfo 获取 HDC 调试信息（用于诊断）
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetHdcDebugInfo() {
    return $Call.ByID(1183190284).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetHdcVersion 获取 HDC 版本
 * @returns {$CancellablePromise<string>}
 */
export function GetHdcVersion() {
    return $Call.ByID(2707463295);
}

/**
 * GetLogFilePath 获取当前日志文件路径
 * @returns {$CancellablePromise<string>}
 */
export function GetLogFilePath() {
    return $Call.ByID(84670795);
}

/**
 * GetMemoryDetailInfo 获取详细内存信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.MemoryDetailInfo | null>}
 */
export function GetMemoryDetailInfo(connectKey) {
    return $Call.ByID(1931030450, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * GetMemoryInfo 获取内存信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.MemoryInfo | null>}
 */
export function GetMemoryInfo(connectKey) {
    return $Call.ByID(2598198943, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetMissionList 获取任务列表
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetMissionList(connectKey) {
    return $Call.ByID(3891948274, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetNetworkInfo 获取网络信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.NetworkInfo[]>}
 */
export function GetNetworkInfo(connectKey) {
    return $Call.ByID(157402718, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetNetworkTrafficInfo 获取网络流量信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.NetworkTrafficInfo[]>}
 */
export function GetNetworkTrafficInfo(connectKey) {
    return $Call.ByID(3479476303, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetOnlineAppInfo 从华为应用市场获取应用信息（名称和图标）
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.OnlineAppInfo | null>}
 */
export function GetOnlineAppInfo(packageName) {
    return $Call.ByID(3071024862, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * GetPhoneAgentStatus 获取Agent状态
 * sessionID: 会话ID
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetPhoneAgentStatus(sessionID) {
    return $Call.ByID(2700296055, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetProcessDetail 获取进程详细信息
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetProcessDetail(connectKey, pid) {
    return $Call.ByID(3698335652, connectKey, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetProcessList 获取进程列表
 * sortBy: 排序字段，默认按内存排序
 * @param {string} connectKey
 * @param {string} sortBy
 * @returns {$CancellablePromise<hdc$0.ProcessListResult | null>}
 */
export function GetProcessList(connectKey, sortBy) {
    return $Call.ByID(1570664113, connectKey, sortBy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * GetProcessListAsync 异步获取进程列表
 * 使用 goroutine + channel 实现异步处理，通过事件推送结果
 * connectKey: 设备标识
 * sortBy: 排序字段
 * @param {string} connectKey
 * @param {string} sortBy
 * @returns {$CancellablePromise<void>}
 */
export function GetProcessListAsync(connectKey, sortBy) {
    return $Call.ByID(1286176651, connectKey, sortBy);
}

/**
 * GetRequests 获取请求列表（合并该设备所有端口的请求）
 * @param {string} deviceId
 * @param {number} limit
 * @returns {$CancellablePromise<$models.NetworkRequest[]>}
 */
export function GetRequests(deviceId, limit) {
    return $Call.ByID(977151182, deviceId, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * GetScreenRecordHistory 获取录屏历史记录
 * @param {string} savePath
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetScreenRecordHistory(savePath) {
    return $Call.ByID(1796571835, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetScreenshotHistory 获取截图历史记录
 * @param {string} savePath
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetScreenshotHistory(savePath) {
    return $Call.ByID(845507900, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetStorageInfo 获取存储信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.StorageInfo | null>}
 */
export function GetStorageInfo(connectKey) {
    return $Call.ByID(1937676417, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * GetSystemProperties 获取所有系统属性
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.SystemProperties>}
 */
export function GetSystemProperties(connectKey) {
    return $Call.ByID(131667808, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * GetSystemRuntime 获取系统运行信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.SystemRuntime | null>}
 */
export function GetSystemRuntime(connectKey) {
    return $Call.ByID(465877503, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * GetUptimeInfo 获取系统运行时间信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetUptimeInfo(connectKey) {
    return $Call.ByID(2362026680, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetUserDocumentsDirectory 获取用户文档目录
 * @returns {$CancellablePromise<string>}
 */
export function GetUserDocumentsDirectory() {
    return $Call.ByID(3893861390);
}

/**
 * GetUserDownloadsDirectory 获取用户下载目录
 * @returns {$CancellablePromise<string>}
 */
export function GetUserDownloadsDirectory() {
    return $Call.ByID(1580539519);
}

/**
 * GetUserHomeDirectory 获取用户主目录
 * @returns {$CancellablePromise<string>}
 */
export function GetUserHomeDirectory() {
    return $Call.ByID(3524606875);
}

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(347461909, name);
}

/**
 * InstallApp 安装应用，支持ZIP和GZIP压缩包
 * @param {string} connectKey
 * @param {string} filePath
 * @param {boolean} replace
 * @param {boolean} sharedBundle
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function InstallApp(connectKey, filePath, replace, sharedBundle) {
    return $Call.ByID(445506738, connectKey, filePath, replace, sharedBundle).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * IsPanelWindowOpen 判断指定菜单的独立窗口是否已打开
 * @param {string} menuId
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPanelWindowOpen(menuId) {
    return $Call.ByID(2783867102, menuId);
}

/**
 * KillProcess 终止进程
 * connectKey: 设备标识
 * pid: 进程 ID
 * force: 是否强制终止
 * @param {string} connectKey
 * @param {number} pid
 * @param {boolean} force
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function KillProcess(connectKey, pid, force) {
    return $Call.ByID(2416160113, connectKey, pid, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * KillServer 终止服务
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function KillServer() {
    return $Call.ByID(1044002335).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListAdbDevices 获取安卓设备列表
 * @param {boolean} verbose
 * @returns {$CancellablePromise<device$0.Device[]>}
 */
export function ListAdbDevices(verbose) {
    return $Call.ByID(31994684, verbose).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * ListAllDevices 获取所有设备（鸿蒙 + 安卓）
 * @param {boolean} verbose
 * @returns {$CancellablePromise<device$0.Device[]>}
 */
export function ListAllDevices(verbose) {
    return $Call.ByID(858837122, verbose).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * ListDeviceDirectory 列出设备目录内容
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} path
 * @param {string} platform
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ListDeviceDirectory(connectKey, path, platform) {
    return $Call.ByID(2197270117, connectKey, path, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListDevices 获取设备列表（基础信息）
 * verbose: 是否使用详细模式
 * @param {boolean} verbose
 * @returns {$CancellablePromise<hdc$0.HdcDevice[]>}
 */
export function ListDevices(verbose) {
    return $Call.ByID(3453351991, verbose).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * ListDevicesWithInfo 获取设备列表（包含产品名称、型号等）
 * @returns {$CancellablePromise<hdc$0.HdcDevice[]>}
 */
export function ListDevicesWithInfo() {
    return $Call.ByID(2189308491).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * ListLocalDirectory 列出本地目录内容
 * @param {string} path
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function ListLocalDirectory(path) {
    return $Call.ByID(188550646, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListPortForwards 获取所有端口转发列表
 * @returns {$CancellablePromise<$models.PortForwardItem[]>}
 */
export function ListPortForwards() {
    return $Call.ByID(2471939789).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * OpenBrowser 在系统浏览器中打开URL
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenBrowser(url) {
    return $Call.ByID(1355841812, url);
}

/**
 * OpenFileInSystem 在系统文件管理器中打开文件或文件夹
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenFileInSystem(filePath) {
    return $Call.ByID(2841347420, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenFolder 在文件管理器中打开指定文件夹
 * @param {string} folderPath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenFolder(folderPath) {
    return $Call.ByID(2561452952, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenLogFile 在系统日志查看器中打开日志文件
 * macOS 上使用 Console.app 打开，支持实时流读取
 * @param {string} filePath
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function OpenLogFile(filePath) {
    return $Call.ByID(869715944, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * OpenPanelWindow 在独立窗口中打开指定菜单页
 * menuId: 菜单 ID（如 device-overview）
 * title: 窗口标题
 * 若该菜单的独立窗口已存在，则聚焦显示；否则创建新窗口
 * @param {string} menuId
 * @param {string} title
 * @returns {$CancellablePromise<boolean>}
 */
export function OpenPanelWindow(menuId, title) {
    return $Call.ByID(1641144262, menuId, title);
}

/**
 * OpenScreenshotFile 在文件管理器中打开截图文件并定位
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenScreenshotFile(filePath) {
    return $Call.ByID(270778558, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenScreenshotFolder 在文件管理器中打开截图目录
 * @param {string} savePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenScreenshotFolder(savePath) {
    return $Call.ByID(1677664300, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ParseHapAppInfo 解析 HAP 应用信息，支持ZIP和GZIP压缩包
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HapAppInfo | null>}
 */
export function ParseHapAppInfo(filePath) {
    return $Call.ByID(193090279, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * PressBack 按下返回键
 * 使用 uitest uiInput keyEvent 命令模拟键盘按键
 * KEYCODE_BACK = 2
 * @param {string} deviceSn
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function PressBack(deviceSn) {
    return $Call.ByID(4235139996, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * PressHome 按下 Home 键
 * 使用 uitest uiInput keyEvent 命令模拟键盘按键
 * KEYCODE_HOME = 1
 * @param {string} deviceSn
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function PressHome(deviceSn) {
    return $Call.ByID(2071745024, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * PressKey 按下指定按键
 * keyCode: 按键码，参考 HarmonyOS KeyCode 常量
 * 常用按键码：
 * - 1: KEYCODE_HOME (Home 键)
 * - 2: KEYCODE_BACK (返回键)
 * - 16: KEYCODE_VOLUME_UP (音量+)
 * - 17: KEYCODE_VOLUME_DOWN (音量-)
 * - 18: KEYCODE_POWER (电源键)
 * - 2067: KEYCODE_MENU (菜单键)
 * @param {string} deviceSn
 * @param {number} keyCode
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function PressKey(deviceSn, keyCode) {
    return $Call.ByID(2382894730, deviceSn, keyCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * PullFileFromDevice 从设备拉取文件
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} remotePath
 * @param {string} localPath
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function PullFileFromDevice(connectKey, remotePath, localPath, platform) {
    return $Call.ByID(3520280475, connectKey, remotePath, localPath, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * PushFileToDevice 推送文件到设备
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} localPath
 * @param {string} remotePath
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function PushFileToDevice(connectKey, localPath, remotePath, platform) {
    return $Call.ByID(2180352697, connectKey, localPath, remotePath, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * PushMockConfigToClient 推送Mock配置到Sophon客户端
 * @param {string} deviceId
 * @param {string} configJson
 * @returns {$CancellablePromise<void>}
 */
export function PushMockConfigToClient(deviceId, configJson) {
    return $Call.ByID(2160169874, deviceId, configJson);
}

/**
 * QueryScreenRecordFile 不断查询录屏文件位置，直到找到文件
 * @param {string} connectKey
 * @param {string} fileName
 * @param {number} maxWaitTime
 * @param {number} checkInterval
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function QueryScreenRecordFile(connectKey, fileName, maxWaitTime, checkInterval) {
    return $Call.ByID(871308831, connectKey, fileName, maxWaitTime, checkInterval).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ReadImageAsBase64 读取图片为 base64
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadImageAsBase64(filePath) {
    return $Call.ByID(1315702906, filePath);
}

/**
 * RemovePortForward 删除端口转发
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function RemovePortForward(localPort, devicePort) {
    return $Call.ByID(3813830532, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ResizeShell 调整 Shell 终端大小
 * @param {string} shellId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeShell(shellId, cols, rows) {
    return $Call.ByID(624845078, shellId, cols, rows);
}

/**
 * RestartServer 重启服务
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function RestartServer() {
    return $Call.ByID(2529341996).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SaveLogsToFile 保存日志到文件
 * @param {string} content
 * @param {string} defaultFileName
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function SaveLogsToFile(content, defaultFileName) {
    return $Call.ByID(3179511705, content, defaultFileName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SelectHapFile 选择 HAP 安装包文件
 * @returns {$CancellablePromise<string>}
 */
export function SelectHapFile() {
    return $Call.ByID(543022155);
}

/**
 * SelectScreenshotPath 选择截图保存路径
 * @returns {$CancellablePromise<string>}
 */
export function SelectScreenshotPath() {
    return $Call.ByID(1388235911);
}

/**
 * StartApp 启动应用
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StartApp(connectKey, packageName) {
    return $Call.ByID(359348267, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StartCapture 开始抓包
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function StartCapture(deviceId, localPort, devicePort) {
    return $Call.ByID(3881803938, deviceId, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartCaptureServer 开始抓包（新架构：Hadice作为服务器）
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function StartCaptureServer(deviceId, localPort, devicePort) {
    return $Call.ByID(1273703093, deviceId, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartHilogStream 启动 hilog 日志流
 * @param {string} connectKey
 * @param {{ [_: string]: any }} options
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StartHilogStream(connectKey, options) {
    return $Call.ByID(3505918155, connectKey, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StartPhoneAgent 启动PhoneAgent
 * config: Agent配置
 * 返回会话ID和错误
 * @param {phoneAgent$0.AgentConfig} config
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function StartPhoneAgent(config) {
    return $Call.ByID(4243478389, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartScreenMirror 开始投屏
 * 
 * 实现方式：使用 hypium-driver + agent.so + RPC 模式
 * 原理说明：
 * 1. 使用 hypium-driver 连接到设备的 UiTest 服务
 * 2. 通过 JSON-RPC 调用 startCaptureScreen API
 * 3. 图片数据通过 RPC Socket 以 JPEG 流的形式传输
 * 4. 拦截 RPC Socket 的数据流，分离 JPEG 数据和 JSON 响应
 * scale: 缩放比例（0.0-1.0），默认 0.6
 * @param {string} deviceSn
 * @param {number} scale
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function StartScreenMirror(deviceSn, scale) {
    return $Call.ByID(485991575, deviceSn, scale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartScreenRecord 开始录屏
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function StartScreenRecord(connectKey) {
    return $Call.ByID(4005303473, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartServer 启动服务
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StartServer() {
    return $Call.ByID(4155797995).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StartShell 启动一个本地 Shell 终端
 * shellId: Shell 进程的唯一标识符
 * @param {string} shellId
 * @returns {$CancellablePromise<boolean>}
 */
export function StartShell(shellId) {
    return $Call.ByID(972204690, shellId);
}

/**
 * StopAllHilogStreams 停止所有活跃的日志流
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopAllHilogStreams() {
    return $Call.ByID(67843167).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopAllShells 停止所有 Shell 进程
 * @returns {$CancellablePromise<void>}
 */
export function StopAllShells() {
    return $Call.ByID(1571505120);
}

/**
 * StopApp 停止应用
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopApp(connectKey, packageName) {
    return $Call.ByID(3643944791, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopCapture 停止抓包（停止指定设备的所有端口抓包）
 * @param {string} deviceId
 * @returns {$CancellablePromise<void>}
 */
export function StopCapture(deviceId) {
    return $Call.ByID(3479537830, deviceId);
}

/**
 * StopCapturePort 停止指定端口的抓包
 * @param {string} deviceId
 * @param {number} localPort
 * @returns {$CancellablePromise<void>}
 */
export function StopCapturePort(deviceId, localPort) {
    return $Call.ByID(2740066193, deviceId, localPort);
}

/**
 * StopCaptureServer 停止抓包服务器（新架构）
 * 注意：停止服务器时不会删除服务器对象，以保留历史请求记录
 * @param {string} deviceId
 * @returns {$CancellablePromise<void>}
 */
export function StopCaptureServer(deviceId) {
    return $Call.ByID(2951992545, deviceId);
}

/**
 * StopHilogStream 停止 hilog 日志流
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopHilogStream(connectKey) {
    return $Call.ByID(2079611975, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopPhoneAgent 停止PhoneAgent
 * sessionID: 会话ID
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function StopPhoneAgent(sessionID) {
    return $Call.ByID(3210768353, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StopScreenMirror 停止投屏
 * @param {string} deviceSn
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function StopScreenMirror(deviceSn) {
    return $Call.ByID(3522653459, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StopScreenRecord 停止录屏
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopScreenRecord(connectKey) {
    return $Call.ByID(1867136533, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopShell 停止 Shell 进程
 * @param {string} shellId
 * @returns {$CancellablePromise<void>}
 */
export function StopShell(shellId) {
    return $Call.ByID(816634422, shellId);
}

/**
 * TakeScreenshot 截取设备屏幕截图
 * @param {string} connectKey
 * @param {string} savePath
 * @param {string} format
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function TakeScreenshot(connectKey, savePath, format) {
    return $Call.ByID(3735813107, connectKey, savePath, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TestConnection 测试连接
 * @param {number} localPort
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function TestConnection(localPort) {
    return $Call.ByID(873322816, localPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchDown 触摸按下事件
 * 使用 uitest uiInput longClick 模拟按下（因为 uitest 没有单独的 down 事件）
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function TouchDown(deviceSn, x, y) {
    return $Call.ByID(3616769775, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchMove 触摸移动事件
 * uitest uiInput 不支持单独的移动事件，此方法保留用于兼容但降级为滑动
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function TouchMove(deviceSn, x, y) {
    return $Call.ByID(3097443642, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchMoveFromTo 触摸从起点移动到终点
 * @param {string} deviceSn
 * @param {number} startX
 * @param {number} startY
 * @param {number} endX
 * @param {number} endY
 * @param {number} smoothTime
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function TouchMoveFromTo(deviceSn, startX, startY, endX, endY, smoothTime) {
    return $Call.ByID(2721101347, deviceSn, startX, startY, endX, endY, smoothTime).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchUp 触摸抬起事件
 * 使用 uitest uiInput click 模拟抬起
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function TouchUp(deviceSn, x, y) {
    return $Call.ByID(949162598, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * UninstallApp 卸载应用
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function UninstallApp(connectKey, packageName) {
    return $Call.ByID(358100317, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * WaitForDevice 等待设备连接
 * connectKey: 可选的设备标识符，如果为空则等待任意设备
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function WaitForDevice(connectKey) {
    return $Call.ByID(1696696402, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * WriteToShell 向 Shell 写入数据
 * @param {string} shellId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToShell(shellId, data) {
    return $Call.ByID(3583896360, shellId, data);
}

// Private type creation functions
const $$createType0 = device$0.CommandResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PortForwardStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = hdc$0.HdcResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = adb$0.AdbResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = hdc$0.AppListResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType5);
const $$createType13 = hdc$0.BatteryInfo.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = hdc$0.CpuDetailInfo.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = hdc$0.CpuUsageInfo.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = hdc$0.DeviceDetailInfo.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = hdc$0.DeviceInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.DisplaySize.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = hdc$0.GraphicsInfo.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = hdc$0.MemoryDetailInfo.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = hdc$0.MemoryInfo.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = hdc$0.NetworkInfo.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = hdc$0.NetworkTrafficInfo.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = hdc$0.OnlineAppInfo.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = hdc$0.ProcessListResult.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = $models.NetworkRequest.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = hdc$0.StorageInfo.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
var $$createType43 = /** @type {(...args: any[]) => any} */(function $$initCreateType43(...args) {
    if ($$createType43 === $$initCreateType43) {
        $$createType43 = $$createType4;
    }
    return $$createType43(...args);
});
const $$createType44 = hdc$0.SystemRuntime.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = device$0.Device.createFrom;
const $$createType47 = $Create.Array($$createType46);
const $$createType48 = hdc$0.HdcDevice.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = $models.PortForwardItem.createFrom;
const $$createType51 = $Create.Array($$createType50);
const $$createType52 = hdc$0.HapAppInfo.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
