// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DisplaySize 屏幕尺寸
 */
export class DisplaySize {
    /**
     * Creates a new DisplaySize instance.
     * @param {Partial<DisplaySize>} [$$source = {}] - The source object to create the DisplaySize.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplaySize instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DisplaySize}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisplaySize(/** @type {Partial<DisplaySize>} */($$parsedSource));
    }
}

/**
 * HttpExtra HTTP Extra信息
 */
export class HttpExtra {
    /**
     * Creates a new HttpExtra instance.
     * @param {Partial<HttpExtra>} [$$source = {}] - The source object to create the HttpExtra.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("reqTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reqTime"] = 0;
        }
        if (!("respTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["respTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpExtra instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HttpExtra}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HttpExtra(/** @type {Partial<HttpExtra>} */($$parsedSource));
    }
}

/**
 * NetworkRequest 网络请求数据
 */
export class NetworkRequest {
    /**
     * Creates a new NetworkRequest instance.
     * @param {Partial<NetworkRequest>} [$$source = {}] - The source object to create the NetworkRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fullUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["statusCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["requestHeaders"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["responseHeaders"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["requestBody"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["responseBody"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rawData"] = undefined;
        }
        if (!("direction" in $$source)) {
            /**
             * request, response
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HttpExtra | null | undefined}
             */
            this["extra"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * URL Query Parameters (来自 data.request.params)
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["requestParams"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 请求基础 URL (来自 data.request.baseURL)
             * @member
             * @type {string | undefined}
             */
            this["baseURL"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 会话边界标记相关字段
             * 是否为会话边界标记
             * @member
             * @type {boolean | undefined}
             */
            this["isSessionBoundary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 边界类型: "disconnect"
             * @member
             * @type {string | undefined}
             */
            this["boundaryType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 客户端ID
             * @member
             * @type {string | undefined}
             */
            this["clientId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 边界信息描述
             * @member
             * @type {string | undefined}
             */
            this["boundaryMessage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkRequest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requestHeaders" in $$parsedSource) {
            $$parsedSource["requestHeaders"] = $$createField6_0($$parsedSource["requestHeaders"]);
        }
        if ("responseHeaders" in $$parsedSource) {
            $$parsedSource["responseHeaders"] = $$createField7_0($$parsedSource["responseHeaders"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField12_0($$parsedSource["extra"]);
        }
        if ("requestParams" in $$parsedSource) {
            $$parsedSource["requestParams"] = $$createField13_0($$parsedSource["requestParams"]);
        }
        return new NetworkRequest(/** @type {Partial<NetworkRequest>} */($$parsedSource));
    }
}

/**
 * PortForwardItem 端口转发项
 */
export class PortForwardItem {
    /**
     * Creates a new PortForwardItem instance.
     * @param {Partial<PortForwardItem>} [$$source = {}] - The source object to create the PortForwardItem.
     */
    constructor($$source = {}) {
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("devicePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["devicePort"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * Forward, Reverse
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForwardItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardItem(/** @type {Partial<PortForwardItem>} */($$parsedSource));
    }
}

/**
 * PortForwardStatus 端口转发状态
 */
export class PortForwardStatus {
    /**
     * Creates a new PortForwardStatus instance.
     * @param {Partial<PortForwardStatus>} [$$source = {}] - The source object to create the PortForwardStatus.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("devicePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["devicePort"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * normal, error, not_configured
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForwardStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardStatus(/** @type {Partial<PortForwardStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = HttpExtra.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
