// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentConfig Agent配置
 */
export class AgentConfig {
    /**
     * Creates a new AgentConfig instance.
     * @param {Partial<AgentConfig>} [$$source = {}] - The source object to create the AgentConfig.
     */
    constructor($$source = {}) {
        if (!("maxSteps" in $$source)) {
            /**
             * 最大执行步数，默认100
             * @member
             * @type {number}
             */
            this["maxSteps"] = 0;
        }
        if (!("deviceID" in $$source)) {
            /**
             * 设备标识符
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("llmConfig" in $$source)) {
            /**
             * LLM配置
             * @member
             * @type {LLMConfig}
             */
            this["llmConfig"] = (new LLMConfig());
        }
        if (!("language" in $$source)) {
            /**
             * 语言，默认"cn"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            /**
             * 系统提示词（可选）
             * @member
             * @type {string}
             */
            this["systemPrompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("llmConfig" in $$parsedSource) {
            $$parsedSource["llmConfig"] = $$createField2_0($$parsedSource["llmConfig"]);
        }
        return new AgentConfig(/** @type {Partial<AgentConfig>} */($$parsedSource));
    }
}

/**
 * LLMConfig LLM配置
 */
export class LLMConfig {
    /**
     * Creates a new LLMConfig instance.
     * @param {Partial<LLMConfig>} [$$source = {}] - The source object to create the LLMConfig.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * 服务提供商
             * @member
             * @type {LLMProvider}
             */
            this["provider"] = LLMProvider.$zero;
        }
        if (!("apiKey" in $$source)) {
            /**
             * API密钥
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("baseURL" in $$source)) {
            /**
             * API基础URL（可选，用于自定义端点）
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * 模型名称
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("maxTokens" in $$source)) {
            /**
             * 最大token数
             * @member
             * @type {number}
             */
            this["maxTokens"] = 0;
        }
        if (!("temperature" in $$source)) {
            /**
             * 温度参数（0-1）
             * @member
             * @type {number}
             */
            this["temperature"] = 0;
        }
        if (!("topP" in $$source)) {
            /**
             * TopP参数（0-1）
             * @member
             * @type {number}
             */
            this["topP"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfig(/** @type {Partial<LLMConfig>} */($$parsedSource));
    }
}

/**
 * LLMProvider LLM服务提供商类型
 * @readonly
 * @enum {string}
 */
export const LLMProvider = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ProviderZhipuAI 智谱AI
     */
    ProviderZhipuAI: "zhipu",

    /**
     * ProviderOpenAI OpenAI
     */
    ProviderOpenAI: "openai",
};

// Private type creation functions
const $$createType0 = LLMConfig.createFrom;
