// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AppInfo,
    AppListResult,
    AppStats,
    BatteryInfo,
    CpuDetailInfo,
    CpuUsageInfo,
    DeviceDetailInfo,
    DeviceInfo,
    GraphicsInfo,
    HapAppInfo,
    HdcDevice,
    HdcResult,
    MemoryDetailInfo,
    MemoryInfo,
    NetworkInfo,
    NetworkTrafficInfo,
    OnlineAppInfo,
    ProcessInfo,
    ProcessListResult,
    ProcessStats,
    StorageInfo,
    SystemRuntime
} from "./models.js";

import * as $models from "./models.js";

/**
 * SystemProperties 系统属性
 * @typedef {$models.SystemProperties} SystemProperties
 */
