// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfo 应用信息
 */
export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("packageName" in $$source)) {
            /**
             * 包名
             * @member
             * @type {string}
             */
            this["packageName"] = "";
        }
        if (!("appName" in $$source)) {
            /**
             * 应用名称
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * 版本名称
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("versionCode" in $$source)) {
            /**
             * 版本号
             * @member
             * @type {number}
             */
            this["versionCode"] = 0;
        }
        if (!("size" in $$source)) {
            /**
             * 应用大小（字节）
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("icon" in $$source)) {
            /**
             * 应用图标（base64 data URL）
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("isSystemApp" in $$source)) {
            /**
             * 是否为系统应用
             * @member
             * @type {boolean}
             */
            this["isSystemApp"] = false;
        }
        if (!("isRunning" in $$source)) {
            /**
             * 是否正在运行
             * @member
             * @type {boolean}
             */
            this["isRunning"] = false;
        }
        if (!("isEnabled" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean}
             */
            this["isEnabled"] = false;
        }
        if (!("installTime" in $$source)) {
            /**
             * 安装时间戳
             * @member
             * @type {number}
             */
            this["installTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

/**
 * AppListResult 应用列表结果
 */
export class AppListResult {
    /**
     * Creates a new AppListResult instance.
     * @param {Partial<AppListResult>} [$$source = {}] - The source object to create the AppListResult.
     */
    constructor($$source = {}) {
        if (!("stats" in $$source)) {
            /**
             * 统计信息
             * @member
             * @type {AppStats}
             */
            this["stats"] = (new AppStats());
        }
        if (!("apps" in $$source)) {
            /**
             * 应用列表
             * @member
             * @type {AppInfo[]}
             */
            this["apps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppListResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField0_0($$parsedSource["stats"]);
        }
        if ("apps" in $$parsedSource) {
            $$parsedSource["apps"] = $$createField1_0($$parsedSource["apps"]);
        }
        return new AppListResult(/** @type {Partial<AppListResult>} */($$parsedSource));
    }
}

/**
 * AppStats 应用统计信息
 */
export class AppStats {
    /**
     * Creates a new AppStats instance.
     * @param {Partial<AppStats>} [$$source = {}] - The source object to create the AppStats.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * 总应用数
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("system" in $$source)) {
            /**
             * 系统应用数
             * @member
             * @type {number}
             */
            this["system"] = 0;
        }
        if (!("thirdParty" in $$source)) {
            /**
             * 第三方应用数
             * @member
             * @type {number}
             */
            this["thirdParty"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * 运行中的应用数
             * @member
             * @type {number}
             */
            this["running"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppStats(/** @type {Partial<AppStats>} */($$parsedSource));
    }
}

/**
 * BatteryInfo 电池信息
 */
export class BatteryInfo {
    /**
     * Creates a new BatteryInfo instance.
     * @param {Partial<BatteryInfo>} [$$source = {}] - The source object to create the BatteryInfo.
     */
    constructor($$source = {}) {
        if (!("capacity" in $$source)) {
            /**
             * 电量百分比
             * @member
             * @type {number}
             */
            this["capacity"] = 0;
        }
        if (!("temperature" in $$source)) {
            /**
             * 温度 (℃)
             * @member
             * @type {number}
             */
            this["temperature"] = 0;
        }
        if (!("voltage" in $$source)) {
            /**
             * 电压 (mV)
             * @member
             * @type {number}
             */
            this["voltage"] = 0;
        }
        if (!("chargingStatus" in $$source)) {
            /**
             * 充电状态
             * @member
             * @type {string}
             */
            this["chargingStatus"] = "";
        }
        if (!("pluggedType" in $$source)) {
            /**
             * 充电类型
             * @member
             * @type {string}
             */
            this["pluggedType"] = "";
        }
        if (!("technology" in $$source)) {
            /**
             * 电池技术
             * @member
             * @type {string}
             */
            this["technology"] = "";
        }
        if (!("health" in $$source)) {
            /**
             * 健康状态
             * @member
             * @type {string}
             */
            this["health"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatteryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatteryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatteryInfo(/** @type {Partial<BatteryInfo>} */($$parsedSource));
    }
}

/**
 * CpuDetailInfo 详细 CPU 使用信息
 */
export class CpuDetailInfo {
    /**
     * Creates a new CpuDetailInfo instance.
     * @param {Partial<CpuDetailInfo>} [$$source = {}] - The source object to create the CpuDetailInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user"] = 0;
        }
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["system"] = 0;
        }
        if (!("kernel" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["kernel"] = 0;
        }
        if (!("idle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idle"] = 0;
        }
        if (!("iowait" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iowait"] = 0;
        }
        if (!("irq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["irq"] = 0;
        }
        if (!("loadAverage" in $$source)) {
            /**
             * @member
             * @type {{"one": number, "five": number, "fifteen": number}}
             */
            this["loadAverage"] = {"one": 0, "five": 0, "fifteen": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CpuDetailInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CpuDetailInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CpuDetailInfo(/** @type {Partial<CpuDetailInfo>} */($$parsedSource));
    }
}

/**
 * CpuUsageInfo CPU 使用信息
 */
export class CpuUsageInfo {
    /**
     * Creates a new CpuUsageInfo instance.
     * @param {Partial<CpuUsageInfo>} [$$source = {}] - The source object to create the CpuUsageInfo.
     */
    constructor($$source = {}) {
        if (!("usagePercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usagePercent"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user"] = 0;
        }
        if (!("system" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["system"] = 0;
        }
        if (!("idle" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idle"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CpuUsageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CpuUsageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CpuUsageInfo(/** @type {Partial<CpuUsageInfo>} */($$parsedSource));
    }
}

/**
 * DeviceDetailInfo 设备完整详细信息
 */
export class DeviceDetailInfo {
    /**
     * Creates a new DeviceDetailInfo instance.
     * @param {Partial<DeviceDetailInfo>} [$$source = {}] - The source object to create the DeviceDetailInfo.
     */
    constructor($$source = {}) {
        if (!("productName" in $$source)) {
            /**
             * 基本信息
             * @member
             * @type {string}
             */
            this["productName"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("brand" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["brand"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("deviceType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceType"] = "";
        }
        if (!("serialNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serialNumber"] = "";
        }
        if (!("osName" in $$source)) {
            /**
             * 系统信息
             * @member
             * @type {string}
             */
            this["osName"] = "";
        }
        if (!("osVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["osVersion"] = "";
        }
        if (!("apiVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiVersion"] = "";
        }
        if (!("softwareVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["softwareVersion"] = "";
        }
        if (!("ohosFullName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ohosFullName"] = "";
        }
        if (!("securityPatch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["securityPatch"] = "";
        }
        if (!("kernelVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kernelVersion"] = "";
        }
        if (!("cpuAbi" in $$source)) {
            /**
             * 硬件信息
             * @member
             * @type {string}
             */
            this["cpuAbi"] = "";
        }
        if (!("hardwareVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hardwareVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceDetailInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceDetailInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceDetailInfo(/** @type {Partial<DeviceDetailInfo>} */($$parsedSource));
    }
}

/**
 * DeviceInfo 设备基本信息（产品名称和型号）
 */
export class DeviceInfo {
    /**
     * Creates a new DeviceInfo instance.
     * @param {Partial<DeviceInfo>} [$$source = {}] - The source object to create the DeviceInfo.
     */
    constructor($$source = {}) {
        if (!("productName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["productName"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo(/** @type {Partial<DeviceInfo>} */($$parsedSource));
    }
}

/**
 * GraphicsInfo 图形性能信息
 */
export class GraphicsInfo {
    /**
     * Creates a new GraphicsInfo instance.
     * @param {Partial<GraphicsInfo>} [$$source = {}] - The source object to create the GraphicsInfo.
     */
    constructor($$source = {}) {
        if (!("gpuVendor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gpuVendor"] = "";
        }
        if (!("gpuRenderer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gpuRenderer"] = "";
        }
        if (!("gpuVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gpuVersion"] = "";
        }
        if (!("surfaceMemory" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["surfaceMemory"] = 0;
        }
        if (!("fpsCount" in $$source)) {
            /**
             * @member
             * @type {{"fps60": number, "fps90": number, "fps120": number}}
             */
            this["fpsCount"] = {"fps60": 0, "fps90": 0, "fps120": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphicsInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphicsInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphicsInfo(/** @type {Partial<GraphicsInfo>} */($$parsedSource));
    }
}

/**
 * HapAppInfo HAP应用信息
 */
export class HapAppInfo {
    /**
     * Creates a new HapAppInfo instance.
     * @param {Partial<HapAppInfo>} [$$source = {}] - The source object to create the HapAppInfo.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileSize"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["extractedHapPath"] = undefined;
        }
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_: string]: string } | undefined}
             */
            this["layeredIcon"] = undefined;
        }
        if (!("bundleName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bundleName"] = "";
        }
        if (!("versionName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["versionName"] = "";
        }
        if (!("versionCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["versionCode"] = 0;
        }
        if (!("vendor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vendor"] = "";
        }
        if (!("moduleName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["moduleName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["moduleDescription"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["minAPIVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["targetAPIVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["compileSdkVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["compileMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["virtualMachine"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["deviceTypes"] = undefined;
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }[]}
             */
            this["permissions"] = [];
        }
        if (!("abilities" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }[]}
             */
            this["abilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HapAppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HapAppInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        const $$createField17_0 = $$createType4;
        const $$createField18_0 = $$createType6;
        const $$createField19_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layeredIcon" in $$parsedSource) {
            $$parsedSource["layeredIcon"] = $$createField5_0($$parsedSource["layeredIcon"]);
        }
        if ("deviceTypes" in $$parsedSource) {
            $$parsedSource["deviceTypes"] = $$createField17_0($$parsedSource["deviceTypes"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField18_0($$parsedSource["permissions"]);
        }
        if ("abilities" in $$parsedSource) {
            $$parsedSource["abilities"] = $$createField19_0($$parsedSource["abilities"]);
        }
        return new HapAppInfo(/** @type {Partial<HapAppInfo>} */($$parsedSource));
    }
}

/**
 * HdcDevice 设备信息
 */
export class HdcDevice {
    /**
     * Creates a new HdcDevice instance.
     * @param {Partial<HdcDevice>} [$$source = {}] - The source object to create the HdcDevice.
     */
    constructor($$source = {}) {
        if (!("connectKey" in $$source)) {
            /**
             * 设备标识符（序列号或 IP:port）
             * @member
             * @type {string}
             */
            this["connectKey"] = "";
        }
        if (!("connectionType" in $$source)) {
            /**
             * 连接类型：USB 或 TCP
             * @member
             * @type {string}
             */
            this["connectionType"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 连接状态：Connected, Offline, Unauthorized, Unknown
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 设备名称（原始输出）
             * @member
             * @type {string | undefined}
             */
            this["deviceName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 产品名称，如 "HUAWEI Mate 60 Pro"
             * @member
             * @type {string | undefined}
             */
            this["productName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 产品型号，如 "ALN-AL00"
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 显示名称
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HdcDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HdcDevice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HdcDevice(/** @type {Partial<HdcDevice>} */($$parsedSource));
    }
}

/**
 * HdcResult 表示 HDC 命令执行结果
 */
export class HdcResult {
    /**
     * Creates a new HdcResult instance.
     * @param {Partial<HdcResult>} [$$source = {}] - The source object to create the HdcResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HdcResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HdcResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HdcResult(/** @type {Partial<HdcResult>} */($$parsedSource));
    }
}

/**
 * MemoryDetailInfo 详细内存信息
 */
export class MemoryDetailInfo {
    /**
     * Creates a new MemoryDetailInfo instance.
     * @param {Partial<MemoryDetailInfo>} [$$source = {}] - The source object to create the MemoryDetailInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["used"] = 0;
        }
        if (!("free" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["free"] = 0;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["available"] = 0;
        }
        if (!("cached" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cached"] = 0;
        }
        if (!("buffers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["buffers"] = 0;
        }
        if (!("swapTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["swapTotal"] = 0;
        }
        if (!("swapUsed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["swapUsed"] = 0;
        }
        if (!("swapFree" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["swapFree"] = 0;
        }
        if (!("usedPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usedPercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryDetailInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryDetailInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryDetailInfo(/** @type {Partial<MemoryDetailInfo>} */($$parsedSource));
    }
}

/**
 * MemoryInfo 内存信息
 */
export class MemoryInfo {
    /**
     * Creates a new MemoryInfo instance.
     * @param {Partial<MemoryInfo>} [$$source = {}] - The source object to create the MemoryInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * KB
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("free" in $$source)) {
            /**
             * KB
             * @member
             * @type {number}
             */
            this["free"] = 0;
        }
        if (!("available" in $$source)) {
            /**
             * KB
             * @member
             * @type {number}
             */
            this["available"] = 0;
        }
        if (!("cached" in $$source)) {
            /**
             * KB
             * @member
             * @type {number}
             */
            this["cached"] = 0;
        }
        if (!("usedPercent" in $$source)) {
            /**
             * 使用百分比
             * @member
             * @type {number}
             */
            this["usedPercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryInfo(/** @type {Partial<MemoryInfo>} */($$parsedSource));
    }
}

/**
 * NetworkInfo 网络信息
 */
export class NetworkInfo {
    /**
     * Creates a new NetworkInfo instance.
     * @param {Partial<NetworkInfo>} [$$source = {}] - The source object to create the NetworkInfo.
     */
    constructor($$source = {}) {
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("ipAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ipAddress"] = "";
        }
        if (!("macAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["macAddress"] = "";
        }
        if (!("netmask" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["netmask"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInfo(/** @type {Partial<NetworkInfo>} */($$parsedSource));
    }
}

/**
 * NetworkTrafficInfo 网络流量信息
 */
export class NetworkTrafficInfo {
    /**
     * Creates a new NetworkTrafficInfo instance.
     * @param {Partial<NetworkTrafficInfo>} [$$source = {}] - The source object to create the NetworkTrafficInfo.
     */
    constructor($$source = {}) {
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("rxBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rxBytes"] = 0;
        }
        if (!("txBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["txBytes"] = 0;
        }
        if (!("rxPackets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rxPackets"] = 0;
        }
        if (!("txPackets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["txPackets"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkTrafficInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkTrafficInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkTrafficInfo(/** @type {Partial<NetworkTrafficInfo>} */($$parsedSource));
    }
}

export class OnlineAppInfo {
    /**
     * Creates a new OnlineAppInfo instance.
     * @param {Partial<OnlineAppInfo>} [$$source = {}] - The source object to create the OnlineAppInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnlineAppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OnlineAppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OnlineAppInfo(/** @type {Partial<OnlineAppInfo>} */($$parsedSource));
    }
}

/**
 * ProcessInfo 进程信息
 */
export class ProcessInfo {
    /**
     * Creates a new ProcessInfo instance.
     * @param {Partial<ProcessInfo>} [$$source = {}] - The source object to create the ProcessInfo.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("nice" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nice"] = 0;
        }
        if (!("virt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virt"] = "";
        }
        if (!("res" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["res"] = "";
        }
        if (!("shr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shr"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("cpuPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuPercent"] = 0;
        }
        if (!("memPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memPercent"] = 0;
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo(/** @type {Partial<ProcessInfo>} */($$parsedSource));
    }
}

/**
 * ProcessListResult 进程列表结果
 */
export class ProcessListResult {
    /**
     * Creates a new ProcessListResult instance.
     * @param {Partial<ProcessListResult>} [$$source = {}] - The source object to create the ProcessListResult.
     */
    constructor($$source = {}) {
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {ProcessStats}
             */
            this["stats"] = (new ProcessStats());
        }
        if (!("processes" in $$source)) {
            /**
             * @member
             * @type {ProcessInfo[]}
             */
            this["processes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessListResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField0_0($$parsedSource["stats"]);
        }
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField1_0($$parsedSource["processes"]);
        }
        return new ProcessListResult(/** @type {Partial<ProcessListResult>} */($$parsedSource));
    }
}

/**
 * ProcessStats 进程统计信息
 */
export class ProcessStats {
    /**
     * Creates a new ProcessStats instance.
     * @param {Partial<ProcessStats>} [$$source = {}] - The source object to create the ProcessStats.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["running"] = 0;
        }
        if (!("sleeping" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sleeping"] = 0;
        }
        if (!("stopped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stopped"] = 0;
        }
        if (!("zombie" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["zombie"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessStats(/** @type {Partial<ProcessStats>} */($$parsedSource));
    }
}

/**
 * StorageInfo 存储信息
 */
export class StorageInfo {
    /**
     * Creates a new StorageInfo instance.
     * @param {Partial<StorageInfo>} [$$source = {}] - The source object to create the StorageInfo.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["total"] = "";
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["used"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["available"] = "";
        }
        if (!("usedPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usedPercent"] = 0;
        }
        if (!("mountPoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mountPoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageInfo(/** @type {Partial<StorageInfo>} */($$parsedSource));
    }
}

/**
 * SystemProperties 系统属性
 * @typedef {{ [_: string]: string }} SystemProperties
 */

/**
 * SystemRuntime 系统运行状态
 */
export class SystemRuntime {
    /**
     * Creates a new SystemRuntime instance.
     * @param {Partial<SystemRuntime>} [$$source = {}] - The source object to create the SystemRuntime.
     */
    constructor($$source = {}) {
        if (!("uptime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }
        if (!("loadAverage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["loadAverage"] = "";
        }
        if (!("currentTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemRuntime instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemRuntime}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemRuntime(/** @type {Partial<SystemRuntime>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AppStats.createFrom;
const $$createType1 = AppInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ProcessStats.createFrom;
const $$createType8 = ProcessInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
