// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: common_types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfilerPluginState_State int32

const (
	ProfilerPluginState_INITED     ProfilerPluginState_State = 0
	ProfilerPluginState_REGISTERED ProfilerPluginState_State = 1
	ProfilerPluginState_LOADED     ProfilerPluginState_State = 2
	ProfilerPluginState_IN_SESSION ProfilerPluginState_State = 3
)

// Enum value maps for ProfilerPluginState_State.
var (
	ProfilerPluginState_State_name = map[int32]string{
		0: "INITED",
		1: "REGISTERED",
		2: "LOADED",
		3: "IN_SESSION",
	}
	ProfilerPluginState_State_value = map[string]int32{
		"INITED":     0,
		"REGISTERED": 1,
		"LOADED":     2,
		"IN_SESSION": 3,
	}
)

func (x ProfilerPluginState_State) Enum() *ProfilerPluginState_State {
	p := new(ProfilerPluginState_State)
	*p = x
	return p
}

func (x ProfilerPluginState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfilerPluginState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[0].Descriptor()
}

func (ProfilerPluginState_State) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[0]
}

func (x ProfilerPluginState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfilerPluginState_State.Descriptor instead.
func (ProfilerPluginState_State) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1, 0}
}

type ProfilerSessionConfig_Mode int32

const (
	ProfilerSessionConfig_OFFLINE ProfilerSessionConfig_Mode = 0
	ProfilerSessionConfig_ONLINE  ProfilerSessionConfig_Mode = 1
)

// Enum value maps for ProfilerSessionConfig_Mode.
var (
	ProfilerSessionConfig_Mode_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
	}
	ProfilerSessionConfig_Mode_value = map[string]int32{
		"OFFLINE": 0,
		"ONLINE":  1,
	}
)

func (x ProfilerSessionConfig_Mode) Enum() *ProfilerSessionConfig_Mode {
	p := new(ProfilerSessionConfig_Mode)
	*p = x
	return p
}

func (x ProfilerSessionConfig_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfilerSessionConfig_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[1].Descriptor()
}

func (ProfilerSessionConfig_Mode) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[1]
}

func (x ProfilerSessionConfig_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfilerSessionConfig_Mode.Descriptor instead.
func (ProfilerSessionConfig_Mode) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{6, 0}
}

type ProfilerPluginConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PluginSha256        string                 `protobuf:"bytes,2,opt,name=plugin_sha256,json=pluginSha256,proto3" json:"plugin_sha256,omitempty"`
	SampleInterval      uint32                 `protobuf:"varint,3,opt,name=sample_interval,json=sampleInterval,proto3" json:"sample_interval,omitempty"`
	ConfigData          []byte                 `protobuf:"bytes,4,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	Clock               string                 `protobuf:"bytes,5,opt,name=clock,proto3" json:"clock,omitempty"`
	IsProtobufSerialize bool                   `protobuf:"varint,6,opt,name=is_protobuf_serialize,json=isProtobufSerialize,proto3" json:"is_protobuf_serialize,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProfilerPluginConfig) Reset() {
	*x = ProfilerPluginConfig{}
	mi := &file_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerPluginConfig) ProtoMessage() {}

func (x *ProfilerPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerPluginConfig.ProtoReflect.Descriptor instead.
func (*ProfilerPluginConfig) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *ProfilerPluginConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfilerPluginConfig) GetPluginSha256() string {
	if x != nil {
		return x.PluginSha256
	}
	return ""
}

func (x *ProfilerPluginConfig) GetSampleInterval() uint32 {
	if x != nil {
		return x.SampleInterval
	}
	return 0
}

func (x *ProfilerPluginConfig) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *ProfilerPluginConfig) GetClock() string {
	if x != nil {
		return x.Clock
	}
	return ""
}

func (x *ProfilerPluginConfig) GetIsProtobufSerialize() bool {
	if x != nil {
		return x.IsProtobufSerialize
	}
	return false
}

type ProfilerPluginState struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         ProfilerPluginState_State `protobuf:"varint,2,opt,name=state,proto3,enum=ProfilerPluginState_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilerPluginState) Reset() {
	*x = ProfilerPluginState{}
	mi := &file_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerPluginState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerPluginState) ProtoMessage() {}

func (x *ProfilerPluginState) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerPluginState.ProtoReflect.Descriptor instead.
func (*ProfilerPluginState) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

func (x *ProfilerPluginState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfilerPluginState) GetState() ProfilerPluginState_State {
	if x != nil {
		return x.State
	}
	return ProfilerPluginState_INITED
}

type ProfilerPluginData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status         uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Data           []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	TvSec          uint64                 `protobuf:"varint,5,opt,name=tv_sec,json=tvSec,proto3" json:"tv_sec,omitempty"`
	TvNsec         uint64                 `protobuf:"varint,6,opt,name=tv_nsec,json=tvNsec,proto3" json:"tv_nsec,omitempty"`
	Version        string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	SampleInterval uint32                 `protobuf:"varint,8,opt,name=sample_interval,json=sampleInterval,proto3" json:"sample_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfilerPluginData) Reset() {
	*x = ProfilerPluginData{}
	mi := &file_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerPluginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerPluginData) ProtoMessage() {}

func (x *ProfilerPluginData) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerPluginData.ProtoReflect.Descriptor instead.
func (*ProfilerPluginData) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

func (x *ProfilerPluginData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfilerPluginData) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProfilerPluginData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProfilerPluginData) GetTvSec() uint64 {
	if x != nil {
		return x.TvSec
	}
	return 0
}

func (x *ProfilerPluginData) GetTvNsec() uint64 {
	if x != nil {
		return x.TvNsec
	}
	return 0
}

func (x *ProfilerPluginData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProfilerPluginData) GetSampleInterval() uint32 {
	if x != nil {
		return x.SampleInterval
	}
	return 0
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_common_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{3}
}

func (x *GetCapabilitiesRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type ProfilerPluginCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilerPluginCapability) Reset() {
	*x = ProfilerPluginCapability{}
	mi := &file_common_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerPluginCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerPluginCapability) ProtoMessage() {}

func (x *ProfilerPluginCapability) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerPluginCapability.ProtoReflect.Descriptor instead.
func (*ProfilerPluginCapability) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{4}
}

func (x *ProfilerPluginCapability) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProfilerPluginCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        uint32                      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Capabilities  []*ProfilerPluginCapability `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_common_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{5}
}

func (x *GetCapabilitiesResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCapabilitiesResponse) GetCapabilities() []*ProfilerPluginCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ProfilerSessionConfig struct {
	state               protoimpl.MessageState                `protogen:"open.v1"`
	Buffers             []*ProfilerSessionConfig_BufferConfig `protobuf:"bytes,1,rep,name=buffers,proto3" json:"buffers,omitempty"`
	SessionMode         ProfilerSessionConfig_Mode            `protobuf:"varint,2,opt,name=session_mode,json=sessionMode,proto3,enum=ProfilerSessionConfig_Mode" json:"session_mode,omitempty"`
	ResultFile          string                                `protobuf:"bytes,3,opt,name=result_file,json=resultFile,proto3" json:"result_file,omitempty"`
	ResultMaxSize       uint32                                `protobuf:"varint,4,opt,name=result_max_size,json=resultMaxSize,proto3" json:"result_max_size,omitempty"`
	SampleDuration      uint32                                `protobuf:"varint,5,opt,name=sample_duration,json=sampleDuration,proto3" json:"sample_duration,omitempty"`
	KeepAliveTime       uint32                                `protobuf:"varint,6,opt,name=keep_alive_time,json=keepAliveTime,proto3" json:"keep_alive_time,omitempty"`
	DiscardCacheData    bool                                  `protobuf:"varint,7,opt,name=discard_cache_data,json=discardCacheData,proto3" json:"discard_cache_data,omitempty"`
	SplitFile           bool                                  `protobuf:"varint,8,opt,name=split_file,json=splitFile,proto3" json:"split_file,omitempty"`
	SingleFileMaxSizeMb uint32                                `protobuf:"varint,9,opt,name=single_file_max_size_mb,json=singleFileMaxSizeMb,proto3" json:"single_file_max_size_mb,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProfilerSessionConfig) Reset() {
	*x = ProfilerSessionConfig{}
	mi := &file_common_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerSessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerSessionConfig) ProtoMessage() {}

func (x *ProfilerSessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerSessionConfig.ProtoReflect.Descriptor instead.
func (*ProfilerSessionConfig) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{6}
}

func (x *ProfilerSessionConfig) GetBuffers() []*ProfilerSessionConfig_BufferConfig {
	if x != nil {
		return x.Buffers
	}
	return nil
}

func (x *ProfilerSessionConfig) GetSessionMode() ProfilerSessionConfig_Mode {
	if x != nil {
		return x.SessionMode
	}
	return ProfilerSessionConfig_OFFLINE
}

func (x *ProfilerSessionConfig) GetResultFile() string {
	if x != nil {
		return x.ResultFile
	}
	return ""
}

func (x *ProfilerSessionConfig) GetResultMaxSize() uint32 {
	if x != nil {
		return x.ResultMaxSize
	}
	return 0
}

func (x *ProfilerSessionConfig) GetSampleDuration() uint32 {
	if x != nil {
		return x.SampleDuration
	}
	return 0
}

func (x *ProfilerSessionConfig) GetKeepAliveTime() uint32 {
	if x != nil {
		return x.KeepAliveTime
	}
	return 0
}

func (x *ProfilerSessionConfig) GetDiscardCacheData() bool {
	if x != nil {
		return x.DiscardCacheData
	}
	return false
}

func (x *ProfilerSessionConfig) GetSplitFile() bool {
	if x != nil {
		return x.SplitFile
	}
	return false
}

func (x *ProfilerSessionConfig) GetSingleFileMaxSizeMb() uint32 {
	if x != nil {
		return x.SingleFileMaxSizeMb
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RequestId     uint32                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionConfig *ProfilerSessionConfig  `protobuf:"bytes,2,opt,name=session_config,json=sessionConfig,proto3" json:"session_config,omitempty"`
	PluginConfigs []*ProfilerPluginConfig `protobuf:"bytes,3,rep,name=plugin_configs,json=pluginConfigs,proto3" json:"plugin_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_common_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSessionRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CreateSessionRequest) GetSessionConfig() *ProfilerSessionConfig {
	if x != nil {
		return x.SessionConfig
	}
	return nil
}

func (x *CreateSessionRequest) GetPluginConfigs() []*ProfilerPluginConfig {
	if x != nil {
		return x.PluginConfigs
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PluginStatus  []*ProfilerPluginState `protobuf:"bytes,3,rep,name=plugin_status,json=pluginStatus,proto3" json:"plugin_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_common_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSessionResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateSessionResponse) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *CreateSessionResponse) GetPluginStatus() []*ProfilerPluginState {
	if x != nil {
		return x.PluginStatus
	}
	return nil
}

type StartSessionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RequestId     uint32                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     uint32                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UpdateConfigs []*ProfilerPluginConfig `protobuf:"bytes,3,rep,name=update_configs,json=updateConfigs,proto3" json:"update_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_common_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{9}
}

func (x *StartSessionRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *StartSessionRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *StartSessionRequest) GetUpdateConfigs() []*ProfilerPluginConfig {
	if x != nil {
		return x.UpdateConfigs
	}
	return nil
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	PluginStatus  []*ProfilerPluginState `protobuf:"bytes,3,rep,name=plugin_status,json=pluginStatus,proto3" json:"plugin_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_common_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{10}
}

func (x *StartSessionResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StartSessionResponse) GetPluginStatus() []*ProfilerPluginState {
	if x != nil {
		return x.PluginStatus
	}
	return nil
}

type FetchDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AddtionData   []byte                 `protobuf:"bytes,3,opt,name=addtion_data,json=addtionData,proto3" json:"addtion_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDataRequest) Reset() {
	*x = FetchDataRequest{}
	mi := &file_common_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataRequest) ProtoMessage() {}

func (x *FetchDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataRequest.ProtoReflect.Descriptor instead.
func (*FetchDataRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{11}
}

func (x *FetchDataRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FetchDataRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *FetchDataRequest) GetAddtionData() []byte {
	if x != nil {
		return x.AddtionData
	}
	return nil
}

type FetchDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ResponseId    uint32                 `protobuf:"varint,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	PluginData    []*ProfilerPluginData  `protobuf:"bytes,4,rep,name=plugin_data,json=pluginData,proto3" json:"plugin_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDataResponse) Reset() {
	*x = FetchDataResponse{}
	mi := &file_common_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataResponse) ProtoMessage() {}

func (x *FetchDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataResponse.ProtoReflect.Descriptor instead.
func (*FetchDataResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{12}
}

func (x *FetchDataResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FetchDataResponse) GetResponseId() uint32 {
	if x != nil {
		return x.ResponseId
	}
	return 0
}

func (x *FetchDataResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *FetchDataResponse) GetPluginData() []*ProfilerPluginData {
	if x != nil {
		return x.PluginData
	}
	return nil
}

type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_common_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{13}
}

func (x *StopSessionRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *StopSessionRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type StopSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	PluginStatus  []*ProfilerPluginState `protobuf:"bytes,3,rep,name=plugin_status,json=pluginStatus,proto3" json:"plugin_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_common_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{14}
}

func (x *StopSessionResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StopSessionResponse) GetPluginStatus() []*ProfilerPluginState {
	if x != nil {
		return x.PluginStatus
	}
	return nil
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_common_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{15}
}

func (x *DestroySessionRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DestroySessionRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type DestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	PluginStatus  []*ProfilerPluginState `protobuf:"bytes,3,rep,name=plugin_status,json=pluginStatus,proto3" json:"plugin_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionResponse) Reset() {
	*x = DestroySessionResponse{}
	mi := &file_common_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionResponse) ProtoMessage() {}

func (x *DestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionResponse.ProtoReflect.Descriptor instead.
func (*DestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{16}
}

func (x *DestroySessionResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DestroySessionResponse) GetPluginStatus() []*ProfilerPluginState {
	if x != nil {
		return x.PluginStatus
	}
	return nil
}

type KeepSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeepAliveTime uint32                 `protobuf:"varint,3,opt,name=keep_alive_time,json=keepAliveTime,proto3" json:"keep_alive_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepSessionRequest) Reset() {
	*x = KeepSessionRequest{}
	mi := &file_common_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepSessionRequest) ProtoMessage() {}

func (x *KeepSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepSessionRequest.ProtoReflect.Descriptor instead.
func (*KeepSessionRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{17}
}

func (x *KeepSessionRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *KeepSessionRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *KeepSessionRequest) GetKeepAliveTime() uint32 {
	if x != nil {
		return x.KeepAliveTime
	}
	return 0
}

type KeepSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepSessionResponse) Reset() {
	*x = KeepSessionResponse{}
	mi := &file_common_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepSessionResponse) ProtoMessage() {}

func (x *KeepSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepSessionResponse.ProtoReflect.Descriptor instead.
func (*KeepSessionResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{18}
}

func (x *KeepSessionResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ProfilerSessionConfig_BufferConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         uint32                 `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilerSessionConfig_BufferConfig) Reset() {
	*x = ProfilerSessionConfig_BufferConfig{}
	mi := &file_common_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilerSessionConfig_BufferConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilerSessionConfig_BufferConfig) ProtoMessage() {}

func (x *ProfilerSessionConfig_BufferConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilerSessionConfig_BufferConfig.ProtoReflect.Descriptor instead.
func (*ProfilerSessionConfig_BufferConfig) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ProfilerSessionConfig_BufferConfig) GetPages() uint32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

var File_common_types_proto protoreflect.FileDescriptor

const file_common_types_proto_rawDesc = "" +
	"\n" +
	"\x12common_types.proto\"\xe3\x01\n" +
	"\x14ProfilerPluginConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rplugin_sha256\x18\x02 \x01(\tR\fpluginSha256\x12'\n" +
	"\x0fsample_interval\x18\x03 \x01(\rR\x0esampleInterval\x12\x1f\n" +
	"\vconfig_data\x18\x04 \x01(\fR\n" +
	"configData\x12\x14\n" +
	"\x05clock\x18\x05 \x01(\tR\x05clock\x122\n" +
	"\x15is_protobuf_serialize\x18\x06 \x01(\bR\x13isProtobufSerialize\"\x9c\x01\n" +
	"\x13ProfilerPluginState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.ProfilerPluginState.StateR\x05state\"?\n" +
	"\x05State\x12\n" +
	"\n" +
	"\x06INITED\x10\x00\x12\x0e\n" +
	"\n" +
	"REGISTERED\x10\x01\x12\n" +
	"\n" +
	"\x06LOADED\x10\x02\x12\x0e\n" +
	"\n" +
	"IN_SESSION\x10\x03\"\xc7\x01\n" +
	"\x12ProfilerPluginData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x15\n" +
	"\x06tv_sec\x18\x05 \x01(\x04R\x05tvSec\x12\x17\n" +
	"\atv_nsec\x18\x06 \x01(\x04R\x06tvNsec\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12'\n" +
	"\x0fsample_interval\x18\b \x01(\rR\x0esampleInterval\"7\n" +
	"\x16GetCapabilitiesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\"B\n" +
	"\x18ProfilerPluginCapability\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"p\n" +
	"\x17GetCapabilitiesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12=\n" +
	"\fcapabilities\x18\x02 \x03(\v2\x19.ProfilerPluginCapabilityR\fcapabilities\"\xfa\x03\n" +
	"\x15ProfilerSessionConfig\x12=\n" +
	"\abuffers\x18\x01 \x03(\v2#.ProfilerSessionConfig.BufferConfigR\abuffers\x12>\n" +
	"\fsession_mode\x18\x02 \x01(\x0e2\x1b.ProfilerSessionConfig.ModeR\vsessionMode\x12\x1f\n" +
	"\vresult_file\x18\x03 \x01(\tR\n" +
	"resultFile\x12&\n" +
	"\x0fresult_max_size\x18\x04 \x01(\rR\rresultMaxSize\x12'\n" +
	"\x0fsample_duration\x18\x05 \x01(\rR\x0esampleDuration\x12&\n" +
	"\x0fkeep_alive_time\x18\x06 \x01(\rR\rkeepAliveTime\x12,\n" +
	"\x12discard_cache_data\x18\a \x01(\bR\x10discardCacheData\x12\x1d\n" +
	"\n" +
	"split_file\x18\b \x01(\bR\tsplitFile\x124\n" +
	"\x17single_file_max_size_mb\x18\t \x01(\rR\x13singleFileMaxSizeMb\x1a$\n" +
	"\fBufferConfig\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\rR\x05pages\"\x1f\n" +
	"\x04Mode\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\"\xb2\x01\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12=\n" +
	"\x0esession_config\x18\x02 \x01(\v2\x16.ProfilerSessionConfigR\rsessionConfig\x12<\n" +
	"\x0eplugin_configs\x18\x03 \x03(\v2\x15.ProfilerPluginConfigR\rpluginConfigs\"\x89\x01\n" +
	"\x15CreateSessionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x129\n" +
	"\rplugin_status\x18\x03 \x03(\v2\x14.ProfilerPluginStateR\fpluginStatus\"\x91\x01\n" +
	"\x13StartSessionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x12<\n" +
	"\x0eupdate_configs\x18\x03 \x03(\v2\x15.ProfilerPluginConfigR\rupdateConfigs\"i\n" +
	"\x14StartSessionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x129\n" +
	"\rplugin_status\x18\x03 \x03(\v2\x14.ProfilerPluginStateR\fpluginStatus\"s\n" +
	"\x10FetchDataRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x12!\n" +
	"\faddtion_data\x18\x03 \x01(\fR\vaddtionData\"\x9d\x01\n" +
	"\x11FetchDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\rR\n" +
	"responseId\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x124\n" +
	"\vplugin_data\x18\x04 \x03(\v2\x13.ProfilerPluginDataR\n" +
	"pluginData\"R\n" +
	"\x12StopSessionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\"h\n" +
	"\x13StopSessionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x129\n" +
	"\rplugin_status\x18\x03 \x03(\v2\x14.ProfilerPluginStateR\fpluginStatus\"U\n" +
	"\x15DestroySessionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\"k\n" +
	"\x16DestroySessionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x129\n" +
	"\rplugin_status\x18\x03 \x03(\v2\x14.ProfilerPluginStateR\fpluginStatus\"z\n" +
	"\x12KeepSessionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x12&\n" +
	"\x0fkeep_alive_time\x18\x03 \x01(\rR\rkeepAliveTime\"-\n" +
	"\x13KeepSessionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06statusB!Z\x1fHadice/backend/hiprofiler/protob\x06proto3"

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData []byte
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)))
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_common_types_proto_goTypes = []any{
	(ProfilerPluginState_State)(0),             // 0: ProfilerPluginState.State
	(ProfilerSessionConfig_Mode)(0),            // 1: ProfilerSessionConfig.Mode
	(*ProfilerPluginConfig)(nil),               // 2: ProfilerPluginConfig
	(*ProfilerPluginState)(nil),                // 3: ProfilerPluginState
	(*ProfilerPluginData)(nil),                 // 4: ProfilerPluginData
	(*GetCapabilitiesRequest)(nil),             // 5: GetCapabilitiesRequest
	(*ProfilerPluginCapability)(nil),           // 6: ProfilerPluginCapability
	(*GetCapabilitiesResponse)(nil),            // 7: GetCapabilitiesResponse
	(*ProfilerSessionConfig)(nil),              // 8: ProfilerSessionConfig
	(*CreateSessionRequest)(nil),               // 9: CreateSessionRequest
	(*CreateSessionResponse)(nil),              // 10: CreateSessionResponse
	(*StartSessionRequest)(nil),                // 11: StartSessionRequest
	(*StartSessionResponse)(nil),               // 12: StartSessionResponse
	(*FetchDataRequest)(nil),                   // 13: FetchDataRequest
	(*FetchDataResponse)(nil),                  // 14: FetchDataResponse
	(*StopSessionRequest)(nil),                 // 15: StopSessionRequest
	(*StopSessionResponse)(nil),                // 16: StopSessionResponse
	(*DestroySessionRequest)(nil),              // 17: DestroySessionRequest
	(*DestroySessionResponse)(nil),             // 18: DestroySessionResponse
	(*KeepSessionRequest)(nil),                 // 19: KeepSessionRequest
	(*KeepSessionResponse)(nil),                // 20: KeepSessionResponse
	(*ProfilerSessionConfig_BufferConfig)(nil), // 21: ProfilerSessionConfig.BufferConfig
}
var file_common_types_proto_depIdxs = []int32{
	0,  // 0: ProfilerPluginState.state:type_name -> ProfilerPluginState.State
	6,  // 1: GetCapabilitiesResponse.capabilities:type_name -> ProfilerPluginCapability
	21, // 2: ProfilerSessionConfig.buffers:type_name -> ProfilerSessionConfig.BufferConfig
	1,  // 3: ProfilerSessionConfig.session_mode:type_name -> ProfilerSessionConfig.Mode
	8,  // 4: CreateSessionRequest.session_config:type_name -> ProfilerSessionConfig
	2,  // 5: CreateSessionRequest.plugin_configs:type_name -> ProfilerPluginConfig
	3,  // 6: CreateSessionResponse.plugin_status:type_name -> ProfilerPluginState
	2,  // 7: StartSessionRequest.update_configs:type_name -> ProfilerPluginConfig
	3,  // 8: StartSessionResponse.plugin_status:type_name -> ProfilerPluginState
	4,  // 9: FetchDataResponse.plugin_data:type_name -> ProfilerPluginData
	3,  // 10: StopSessionResponse.plugin_status:type_name -> ProfilerPluginState
	3,  // 11: DestroySessionResponse.plugin_status:type_name -> ProfilerPluginState
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		EnumInfos:         file_common_types_proto_enumTypes,
		MessageInfos:      file_common_types_proto_msgTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
