// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: profiler_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_profiler_service_proto protoreflect.FileDescriptor

const file_profiler_service_proto_rawDesc = "" +
	"\n" +
	"\x16profiler_service.proto\x1a\x12common_types.proto2\xc2\x03\n" +
	"\x10IProfilerService\x12D\n" +
	"\x0fGetCapabilities\x12\x17.GetCapabilitiesRequest\x1a\x18.GetCapabilitiesResponse\x12>\n" +
	"\rCreateSession\x12\x15.CreateSessionRequest\x1a\x16.CreateSessionResponse\x12;\n" +
	"\fStartSession\x12\x14.StartSessionRequest\x1a\x15.StartSessionResponse\x124\n" +
	"\tFetchData\x12\x11.FetchDataRequest\x1a\x12.FetchDataResponse0\x01\x128\n" +
	"\vStopSession\x12\x13.StopSessionRequest\x1a\x14.StopSessionResponse\x12A\n" +
	"\x0eDestroySession\x12\x16.DestroySessionRequest\x1a\x17.DestroySessionResponse\x128\n" +
	"\vKeepSession\x12\x13.KeepSessionRequest\x1a\x14.KeepSessionResponseB!Z\x1fHadice/backend/hiprofiler/protob\x06proto3"

var file_profiler_service_proto_goTypes = []any{
	(*GetCapabilitiesRequest)(nil),  // 0: GetCapabilitiesRequest
	(*CreateSessionRequest)(nil),    // 1: CreateSessionRequest
	(*StartSessionRequest)(nil),     // 2: StartSessionRequest
	(*FetchDataRequest)(nil),        // 3: FetchDataRequest
	(*StopSessionRequest)(nil),      // 4: StopSessionRequest
	(*DestroySessionRequest)(nil),   // 5: DestroySessionRequest
	(*KeepSessionRequest)(nil),      // 6: KeepSessionRequest
	(*GetCapabilitiesResponse)(nil), // 7: GetCapabilitiesResponse
	(*CreateSessionResponse)(nil),   // 8: CreateSessionResponse
	(*StartSessionResponse)(nil),    // 9: StartSessionResponse
	(*FetchDataResponse)(nil),       // 10: FetchDataResponse
	(*StopSessionResponse)(nil),     // 11: StopSessionResponse
	(*DestroySessionResponse)(nil),  // 12: DestroySessionResponse
	(*KeepSessionResponse)(nil),     // 13: KeepSessionResponse
}
var file_profiler_service_proto_depIdxs = []int32{
	0,  // 0: IProfilerService.GetCapabilities:input_type -> GetCapabilitiesRequest
	1,  // 1: IProfilerService.CreateSession:input_type -> CreateSessionRequest
	2,  // 2: IProfilerService.StartSession:input_type -> StartSessionRequest
	3,  // 3: IProfilerService.FetchData:input_type -> FetchDataRequest
	4,  // 4: IProfilerService.StopSession:input_type -> StopSessionRequest
	5,  // 5: IProfilerService.DestroySession:input_type -> DestroySessionRequest
	6,  // 6: IProfilerService.KeepSession:input_type -> KeepSessionRequest
	7,  // 7: IProfilerService.GetCapabilities:output_type -> GetCapabilitiesResponse
	8,  // 8: IProfilerService.CreateSession:output_type -> CreateSessionResponse
	9,  // 9: IProfilerService.StartSession:output_type -> StartSessionResponse
	10, // 10: IProfilerService.FetchData:output_type -> FetchDataResponse
	11, // 11: IProfilerService.StopSession:output_type -> StopSessionResponse
	12, // 12: IProfilerService.DestroySession:output_type -> DestroySessionResponse
	13, // 13: IProfilerService.KeepSession:output_type -> KeepSessionResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_profiler_service_proto_init() }
func file_profiler_service_proto_init() {
	if File_profiler_service_proto != nil {
		return
	}
	file_common_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profiler_service_proto_rawDesc), len(file_profiler_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profiler_service_proto_goTypes,
		DependencyIndexes: file_profiler_service_proto_depIdxs,
	}.Build()
	File_profiler_service_proto = out.File
	file_profiler_service_proto_goTypes = nil
	file_profiler_service_proto_depIdxs = nil
}
