// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: profiler_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IProfilerService_GetCapabilities_FullMethodName = "/IProfilerService/GetCapabilities"
	IProfilerService_CreateSession_FullMethodName   = "/IProfilerService/CreateSession"
	IProfilerService_StartSession_FullMethodName    = "/IProfilerService/StartSession"
	IProfilerService_FetchData_FullMethodName       = "/IProfilerService/FetchData"
	IProfilerService_StopSession_FullMethodName     = "/IProfilerService/StopSession"
	IProfilerService_DestroySession_FullMethodName  = "/IProfilerService/DestroySession"
	IProfilerService_KeepSession_FullMethodName     = "/IProfilerService/KeepSession"
)

// IProfilerServiceClient is the client API for IProfilerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IProfilerServiceClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	FetchData(ctx context.Context, in *FetchDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchDataResponse], error)
	StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error)
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	KeepSession(ctx context.Context, in *KeepSessionRequest, opts ...grpc.CallOption) (*KeepSessionResponse, error)
}

type iProfilerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIProfilerServiceClient(cc grpc.ClientConnInterface) IProfilerServiceClient {
	return &iProfilerServiceClient{cc}
}

func (c *iProfilerServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, IProfilerService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iProfilerServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, IProfilerService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iProfilerServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, IProfilerService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iProfilerServiceClient) FetchData(ctx context.Context, in *FetchDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IProfilerService_ServiceDesc.Streams[0], IProfilerService_FetchData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchDataRequest, FetchDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IProfilerService_FetchDataClient = grpc.ServerStreamingClient[FetchDataResponse]

func (c *iProfilerServiceClient) StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSessionResponse)
	err := c.cc.Invoke(ctx, IProfilerService_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iProfilerServiceClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, IProfilerService_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iProfilerServiceClient) KeepSession(ctx context.Context, in *KeepSessionRequest, opts ...grpc.CallOption) (*KeepSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeepSessionResponse)
	err := c.cc.Invoke(ctx, IProfilerService_KeepSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IProfilerServiceServer is the server API for IProfilerService service.
// All implementations must embed UnimplementedIProfilerServiceServer
// for forward compatibility.
type IProfilerServiceServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	FetchData(*FetchDataRequest, grpc.ServerStreamingServer[FetchDataResponse]) error
	StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error)
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	KeepSession(context.Context, *KeepSessionRequest) (*KeepSessionResponse, error)
	mustEmbedUnimplementedIProfilerServiceServer()
}

// UnimplementedIProfilerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIProfilerServiceServer struct{}

func (UnimplementedIProfilerServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedIProfilerServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedIProfilerServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedIProfilerServiceServer) FetchData(*FetchDataRequest, grpc.ServerStreamingServer[FetchDataResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchData not implemented")
}
func (UnimplementedIProfilerServiceServer) StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedIProfilerServiceServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedIProfilerServiceServer) KeepSession(context.Context, *KeepSessionRequest) (*KeepSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeepSession not implemented")
}
func (UnimplementedIProfilerServiceServer) mustEmbedUnimplementedIProfilerServiceServer() {}
func (UnimplementedIProfilerServiceServer) testEmbeddedByValue()                          {}

// UnsafeIProfilerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IProfilerServiceServer will
// result in compilation errors.
type UnsafeIProfilerServiceServer interface {
	mustEmbedUnimplementedIProfilerServiceServer()
}

func RegisterIProfilerServiceServer(s grpc.ServiceRegistrar, srv IProfilerServiceServer) {
	// If the following call panics, it indicates UnimplementedIProfilerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IProfilerService_ServiceDesc, srv)
}

func _IProfilerService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IProfilerServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IProfilerService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IProfilerServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IProfilerService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IProfilerServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IProfilerService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IProfilerServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IProfilerService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IProfilerServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IProfilerService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IProfilerServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IProfilerService_FetchData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IProfilerServiceServer).FetchData(m, &grpc.GenericServerStream[FetchDataRequest, FetchDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IProfilerService_FetchDataServer = grpc.ServerStreamingServer[FetchDataResponse]

func _IProfilerService_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IProfilerServiceServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IProfilerService_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IProfilerServiceServer).StopSession(ctx, req.(*StopSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IProfilerService_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IProfilerServiceServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IProfilerService_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IProfilerServiceServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IProfilerService_KeepSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IProfilerServiceServer).KeepSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IProfilerService_KeepSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IProfilerServiceServer).KeepSession(ctx, req.(*KeepSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IProfilerService_ServiceDesc is the grpc.ServiceDesc for IProfilerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IProfilerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IProfilerService",
	HandlerType: (*IProfilerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _IProfilerService_GetCapabilities_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _IProfilerService_CreateSession_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _IProfilerService_StartSession_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _IProfilerService_StopSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _IProfilerService_DestroySession_Handler,
		},
		{
			MethodName: "KeepSession",
			Handler:    _IProfilerService_KeepSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchData",
			Handler:       _IProfilerService_FetchData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "profiler_service.proto",
}
