// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是 v3 中的服务，提供所有应用功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as adb$0 from "./adb/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "./device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hdc$0 from "./hdc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as phoneAgent$0 from "./phoneAgent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AdbConnectDevice TCP 连接安卓设备
 * @param {string} ipPort
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbConnectDevice(ipPort) {
    return $Call.ByID(3518525135, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AdbDisconnectDevice 断开安卓设备连接
 * @param {string} ipPort
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbDisconnectDevice(ipPort) {
    return $Call.ByID(679027353, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AdbKillServer 终止 ADB 服务
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbKillServer() {
    return $Call.ByID(1959825414).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AdbStartServer 启动 ADB 服务
 * @returns {$CancellablePromise<device$0.CommandResult | null>}
 */
export function AdbStartServer() {
    return $Call.ByID(3795161036).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckPortForwardStatus 检查端口转发状态
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<$models.PortForwardStatus | null>}
 */
export function CheckPortForwardStatus(localPort, devicePort) {
    return $Call.ByID(2160002514, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckReversePortForwardStatus 检查反向端口转发状态
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<$models.PortForwardStatus | null>}
 */
export function CheckReversePortForwardStatus(deviceId, localPort, devicePort) {
    return $Call.ByID(1026069536, deviceId, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckServer 检查服务状态
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function CheckServer() {
    return $Call.ByID(1646747579).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * CheckUpdate 检查更新
 * updateCheckURL: 更新检查JSON的URL地址
 * currentVersion: 当前软件版本号
 * @param {string} updateCheckURL
 * @param {string} currentVersion
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function CheckUpdate(updateCheckURL, currentVersion) {
    return $Call.ByID(2743055505, updateCheckURL, currentVersion).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClearAppCache 清除应用缓存
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ClearAppCache(connectKey, packageName) {
    return $Call.ByID(4034704246, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ClearAppData 清除应用数据
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ClearAppData(connectKey, packageName) {
    return $Call.ByID(1343419524, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ClearAppDataByPlatform 根据平台清除应用数据
 * @param {string} connectKey
 * @param {string} packageName
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ClearAppDataByPlatform(connectKey, packageName, platform) {
    return $Call.ByID(929685238, connectKey, packageName, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ClearAppDiskCache 清除应用磁盘缓存
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ClearAppDiskCache() {
    return $Call.ByID(3414197473).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClearRequests 清空请求列表（清空该设备所有端口的请求）
 * @param {string} deviceId
 * @returns {$CancellablePromise<void>}
 */
export function ClearRequests(deviceId) {
    return $Call.ByID(442765571, deviceId);
}

/**
 * ClearScreenshotHistory 清空截图历史
 * @param {string} savePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ClearScreenshotHistory(savePath) {
    return $Call.ByID(2174065827, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Click 点击事件
 * HarmonyOS: 使用 uitest uiInput click
 * Android: 使用 scrcpy 控制通道或 input tap
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function Click(deviceSn, x, y) {
    return $Call.ByID(1958183776, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClosePanelWindow 关闭指定菜单的独立窗口
 * 若窗口存在则关闭并返回 true，否则返回 false
 * @param {string} menuId
 * @returns {$CancellablePromise<boolean>}
 */
export function ClosePanelWindow(menuId) {
    return $Call.ByID(3789017366, menuId);
}

/**
 * ConfigurePortForward 配置端口转发
 * type参数: "Forward" 使用 fport 命令, "Reverse" 使用 rport 命令
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @param {string} portType
 * @returns {$CancellablePromise<$models.PortForwardStatus | null>}
 */
export function ConfigurePortForward(deviceId, localPort, devicePort, portType) {
    return $Call.ByID(548412788, deviceId, localPort, devicePort, portType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ConnectDevice TCP 连接设备
 * @param {string} ipPort
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ConnectDevice(ipPort) {
    return $Call.ByID(3635677216, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ConnectWirelessDebugDevice 连接无线调试设备。
 * @param {$models.WirelessDebugRequest} req
 * @returns {$CancellablePromise<$models.WirelessDebugResult | null>}
 */
export function ConnectWirelessDebugDevice(req) {
    return $Call.ByID(2593429863, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * CopyFilePathToClipboard 复制文件路径到剪贴板（Finder 风格）
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function CopyFilePathToClipboard(filePath) {
    return $Call.ByID(3874272601, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * CopyImageToClipboard 复制图片到剪贴板
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function CopyImageToClipboard(filePath) {
    return $Call.ByID(2070046983, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * CopyScreenRecordFileToTmp 将录屏文件复制到临时目录
 * @param {string} connectKey
 * @param {string} uri
 * @param {string} originalPath
 * @param {string} fileName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function CopyScreenRecordFileToTmp(connectKey, uri, originalPath, fileName) {
    return $Call.ByID(2405013632, connectKey, uri, originalPath, fileName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DebugGetServerInfo 用于调试：获取服务器状态信息
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function DebugGetServerInfo() {
    return $Call.ByID(2620625566).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DeleteDeviceFile 删除设备上的文件
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} filePath
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DeleteDeviceFile(connectKey, filePath, platform) {
    return $Call.ByID(2997040191, connectKey, filePath, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DeleteLocalFile 删除本地文件
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DeleteLocalFile(filePath) {
    return $Call.ByID(4229012292, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DeleteScreenshot 删除截图文件
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DeleteScreenshot(filePath) {
    return $Call.ByID(405009903, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DisconnectDevice 断开 TCP 连接
 * @param {string} ipPort
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function DisconnectDevice(ipPort) {
    return $Call.ByID(3846116260, ipPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * DownloadScreenRecordFile 下载录屏文件到本地
 * @param {string} connectKey
 * @param {string} devicePath
 * @param {string} savePath
 * @param {string} fileName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function DownloadScreenRecordFile(connectKey, devicePath, savePath, fileName) {
    return $Call.ByID(1821165999, connectKey, devicePath, savePath, fileName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ExecuteAdb 执行任意 ADB 命令
 * @param {string[]} args
 * @returns {$CancellablePromise<adb$0.AdbResult | null>}
 */
export function ExecuteAdb(args) {
    return $Call.ByID(1982736592, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * ExecuteHdc 执行任意 HDC 命令
 * @param {string[]} args
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ExecuteHdc(args) {
    return $Call.ByID(982964504, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} connectKey
 * @param {string} shellCommand
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ExecuteHdcCommand(connectKey, shellCommand) {
    return $Call.ByID(3621870993, connectKey, shellCommand).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ExecutePhoneAgentStep 执行Agent单步操作
 * sessionID: 会话ID
 * task: 任务描述（仅在第一步需要）
 * isFirst: 是否是第一步
 * 返回执行结果
 * @param {string} sessionID
 * @param {string} task
 * @param {boolean} isFirst
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ExecutePhoneAgentStep(sessionID, task, isFirst) {
    return $Call.ByID(970708516, sessionID, task, isFirst).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ExtractVideoFirstFrame 提取视频第一帧并返回 base64 图片数据
 * @param {string} videoPath
 * @returns {$CancellablePromise<string>}
 */
export function ExtractVideoFirstFrame(videoPath) {
    return $Call.ByID(3455542375, videoPath);
}

/**
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function ForceStopApp(connectKey, packageName) {
    return $Call.ByID(4159700774, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} connectKey
 * @param {string} packageName
 * @param {string} platform
 * @returns {$CancellablePromise<$models.CommandResult | null>}
 */
export function ForceStopAppByPlatform(connectKey, packageName, platform) {
    return $Call.ByID(3787202544, connectKey, packageName, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetAdbDebugInfo 获取 ADB 调试信息
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetAdbDebugInfo() {
    return $Call.ByID(2203242744).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAdbVersion 获取 ADB 版本
 * @returns {$CancellablePromise<string>}
 */
export function GetAdbVersion() {
    return $Call.ByID(1809366579);
}

/**
 * GetAndroidAppList 获取安卓设备应用列表
 * @param {string} connectKey
 * @returns {$CancellablePromise<adb$0.AndroidAppListResult | null>}
 */
export function GetAndroidAppList(connectKey) {
    return $Call.ByID(1109081986, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetAndroidCaptureStatus 获取 Android 抓包状态
 * @param {string} deviceId
 * @param {string} packageName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetAndroidCaptureStatus(deviceId, packageName) {
    return $Call.ByID(912525005, deviceId, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAndroidDebuggableApps 获取 Android 可调试应用列表
 * @param {string} deviceId
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetAndroidDebuggableApps(deviceId) {
    return $Call.ByID(2343163503, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetAndroidDeviceList 获取 Android 设备列表
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetAndroidDeviceList() {
    return $Call.ByID(2610377813).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetAndroidPidByPackageName 按包名快速查询当前 PID（用于开始抓包前快速刷新 PID，避免漏请求）
 * 返回 0 表示进程未在运行
 * @param {string} deviceId
 * @param {string} packageName
 * @returns {$CancellablePromise<number>}
 */
export function GetAndroidPidByPackageName(deviceId, packageName) {
    return $Call.ByID(1184730980, deviceId, packageName);
}

/**
 * GetAppFullDetail 获取应用完整详情（包括权限和能力信息）
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetAppFullDetail(connectKey, packageName) {
    return $Call.ByID(846714931, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAppList 获取应用列表
 * incremental: 是否使用渐进式加载（先返回基本列表，然后通过事件推送详情）
 * @param {string} connectKey
 * @param {string} filter
 * @param {boolean} incremental
 * @returns {$CancellablePromise<hdc$0.AppListResult | null>}
 */
export function GetAppList(connectKey, filter, incremental) {
    return $Call.ByID(3478131247, connectKey, filter, incremental).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetAppListByPlatform 根据平台获取应用列表
 * @param {string} connectKey
 * @param {string} filter
 * @param {boolean} incremental
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.AppListResult | null>}
 */
export function GetAppListByPlatform(connectKey, filter, incremental, platform) {
    return $Call.ByID(334570385, connectKey, filter, incremental, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetAppRunningRecords 获取运行中的应用记录
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetAppRunningRecords(connectKey) {
    return $Call.ByID(3295243168, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetAppShortcuts 获取应用快捷方式
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetAppShortcuts(connectKey, packageName) {
    return $Call.ByID(1720030354, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetAppVersion returns the current application version
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(3702145641);
}

/**
 * GetBatteryInfo 获取电池信息（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.BatteryInfo | null>}
 */
export function GetBatteryInfo(connectKey) {
    return $Call.ByID(3923413513, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetBatteryInfoByPlatform 获取电池信息（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.BatteryInfo | null>}
 */
export function GetBatteryInfoByPlatform(connectKey, platform) {
    return $Call.ByID(2358788339, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetCachedAppIcon 获取磁盘缓存的应用图标（base64格式）
 * @param {string} packageName
 * @returns {$CancellablePromise<string>}
 */
export function GetCachedAppIcon(packageName) {
    return $Call.ByID(562933024, packageName);
}

/**
 * GetCachedAppList 获取磁盘缓存的应用列表
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetCachedAppList() {
    return $Call.ByID(1702823729).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCaptureServerStatus 获取新架构抓包状态
 * @param {string} deviceId
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetCaptureServerStatus(deviceId) {
    return $Call.ByID(2611581395, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCaptureStatus 获取抓包状态（返回该设备所有端口的状态）
 * @param {string} deviceId
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetCaptureStatus(deviceId) {
    return $Call.ByID(771041176, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetCpuDetailInfo 获取详细 CPU 使用信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.CpuDetailInfo | null>}
 */
export function GetCpuDetailInfo(connectKey) {
    return $Call.ByID(627764747, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetCpuFreqInfo 获取 CPU 频率信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.CpuFreqInfo | null>}
 */
export function GetCpuFreqInfo(connectKey) {
    return $Call.ByID(27464412, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * GetCpuUsageInfo 获取 CPU 使用信息（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.CpuUsageInfo | null>}
 */
export function GetCpuUsageInfo(connectKey) {
    return $Call.ByID(3834672033, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * GetCpuUsageInfoByPlatform 获取 CPU 使用信息（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.CpuUsageInfo | null>}
 */
export function GetCpuUsageInfoByPlatform(connectKey, platform) {
    return $Call.ByID(4036085131, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetDefaultScreenshotPath 获取默认截图路径
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultScreenshotPath() {
    return $Call.ByID(4018424670);
}

/**
 * GetDeviceDetailInfo 获取设备完整详细信息（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.DeviceDetailInfo | null>}
 */
export function GetDeviceDetailInfo(connectKey) {
    return $Call.ByID(783956267, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetDeviceDetailInfoByPlatform 获取设备详细信息（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.DeviceDetailInfo | null>}
 */
export function GetDeviceDetailInfoByPlatform(connectKey, platform) {
    return $Call.ByID(144683701, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetDeviceInfo 获取设备基本信息（产品名称和型号）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.DeviceInfo | null>}
 */
export function GetDeviceInfo(connectKey) {
    return $Call.ByID(316556094, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * GetDeviceProperty 获取设备属性
 * @param {string} connectKey
 * @param {string} property
 * @returns {$CancellablePromise<string>}
 */
export function GetDeviceProperty(connectKey, property) {
    return $Call.ByID(1853453675, connectKey, property);
}

/**
 * GetDeviceUdid 获取设备UDID（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<string>}
 */
export function GetDeviceUdid(connectKey) {
    return $Call.ByID(1569541410, connectKey);
}

/**
 * GetDeviceUdidByPlatform 获取设备唯一标识（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<string>}
 */
export function GetDeviceUdidByPlatform(connectKey, platform) {
    return $Call.ByID(805900132, connectKey, platform);
}

/**
 * GetDisplaySize 获取屏幕尺寸
 * @param {string} deviceSn
 * @returns {$CancellablePromise<$models.DisplaySize | null>}
 */
export function GetDisplaySize(deviceSn) {
    return $Call.ByID(2024825347, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * GetFaultLogDetail 获取故障日志详情
 * @param {string} connectKey
 * @param {string} recordId
 * @returns {$CancellablePromise<string>}
 */
export function GetFaultLogDetail(connectKey, recordId) {
    return $Call.ByID(2629597315, connectKey, recordId);
}

/**
 * GetFaultLogList 获取故障日志列表
 * @param {string} connectKey
 * @param {string} processName
 * @param {number} n
 * @returns {$CancellablePromise<hdc$0.FaultLogEntry[]>}
 */
export function GetFaultLogList(connectKey, processName, n) {
    return $Call.ByID(3017542990, connectKey, processName, n).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * GetFileInfo 获取文件信息
 * @param {string} filePath
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetFileInfo(filePath) {
    return $Call.ByID(3398976314, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetGraphicsInfo 获取图形性能信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.GraphicsInfo | null>}
 */
export function GetGraphicsInfo(connectKey) {
    return $Call.ByID(3639539489, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * GetGraphicsInfoWithPid 获取图形性能信息（带 PID，用于安卓 FPS）
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<hdc$0.GraphicsInfo | null>}
 */
export function GetGraphicsInfoWithPid(connectKey, pid) {
    return $Call.ByID(3279553938, connectKey, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * GetHadiceOutputDirectory 获取并创建 ~/Documents/Hadice 下的输出目录。
 * @param {string} subdir
 * @returns {$CancellablePromise<string>}
 */
export function GetHadiceOutputDirectory(subdir) {
    return $Call.ByID(919756780, subdir);
}

/**
 * GetHdcDebugInfo 获取 HDC 调试信息（用于诊断）
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetHdcDebugInfo() {
    return $Call.ByID(389238872).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetHdcVersion 获取 HDC 版本
 * @returns {$CancellablePromise<string>}
 */
export function GetHdcVersion() {
    return $Call.ByID(487407571);
}

/**
 * GetHiProfilerApps 获取鸿蒙设备上可调试的应用列表（HiProfiler 模式）
 * @param {string} deviceId
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetHiProfilerApps(deviceId) {
    return $Call.ByID(13879218, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetHiProfilerCaptureStatus 获取指定设备当前的 HiProfiler 会话状态。
 * @param {string} deviceId
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetHiProfilerCaptureStatus(deviceId) {
    return $Call.ByID(314301030, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetHiProfilerProcessStatus 按完整进程名查询当前运行状态和 PID。
 * @param {string} deviceId
 * @param {string} processName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetHiProfilerProcessStatus(deviceId, processName) {
    return $Call.ByID(57341189, deviceId, processName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetIpcStat 获取 IPC 统计数据
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<hdc$0.IpcStatInfo | null>}
 */
export function GetIpcStat(connectKey, pid) {
    return $Call.ByID(313627256, connectKey, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * GetLogFilePath 获取当前日志文件路径
 * @returns {$CancellablePromise<string>}
 */
export function GetLogFilePath() {
    return $Call.ByID(3099510663);
}

/**
 * GetMemoryDetailInfo 获取详细内存信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.MemoryDetailInfo | null>}
 */
export function GetMemoryDetailInfo(connectKey) {
    return $Call.ByID(374635846, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * GetMemoryInfo 获取内存信息（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.MemoryInfo | null>}
 */
export function GetMemoryInfo(connectKey) {
    return $Call.ByID(885930963, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * GetMemoryInfoByPlatform 获取内存信息（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.MemoryInfo | null>}
 */
export function GetMemoryInfoByPlatform(connectKey, platform) {
    return $Call.ByID(1274214269, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * GetMissionList 获取任务列表
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetMissionList(connectKey) {
    return $Call.ByID(1849604014, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetNetworkInfo 获取网络信息（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.NetworkInfo[]>}
 */
export function GetNetworkInfo(connectKey) {
    return $Call.ByID(1680508690, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * GetNetworkInfoByPlatform 获取网络信息（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.NetworkInfo[]>}
 */
export function GetNetworkInfoByPlatform(connectKey, platform) {
    return $Call.ByID(3234409044, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType54($result);
    }));
}

/**
 * GetNetworkTrafficInfo 获取网络流量信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.NetworkTrafficInfo[]>}
 */
export function GetNetworkTrafficInfo(connectKey) {
    return $Call.ByID(1827983987, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType56($result);
    }));
}

/**
 * GetOnlineAppInfo 从华为应用市场获取应用信息（名称和图标）
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.OnlineAppInfo | null>}
 */
export function GetOnlineAppInfo(packageName) {
    return $Call.ByID(81609154, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType58($result);
    }));
}

/**
 * GetPhoneAgentStatus 获取Agent状态
 * sessionID: 会话ID
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetPhoneAgentStatus(sessionID) {
    return $Call.ByID(3882824243, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetProcessCpuUsage 获取进程级 CPU 使用率
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<hdc$0.ProcessCpuEntry[]>}
 */
export function GetProcessCpuUsage(connectKey, pid) {
    return $Call.ByID(3429512544, connectKey, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType60($result);
    }));
}

/**
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetProcessDetail(connectKey, pid) {
    return $Call.ByID(2760150488, connectKey, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} connectKey
 * @param {number} pid
 * @param {string} platform
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetProcessDetailByPlatform(connectKey, pid, platform) {
    return $Call.ByID(4181755554, connectKey, pid, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetProcessIOInfo 获取进程 IO 信息
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<hdc$0.ProcessIOInfo | null>}
 */
export function GetProcessIOInfo(connectKey, pid) {
    return $Call.ByID(3916805869, connectKey, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType62($result);
    }));
}

/**
 * @param {string} connectKey
 * @param {string} sortBy
 * @returns {$CancellablePromise<$models.ProcessListResult | null>}
 */
export function GetProcessList(connectKey, sortBy) {
    return $Call.ByID(3730783157, connectKey, sortBy).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType64($result);
    }));
}

/**
 * @param {string} connectKey
 * @param {string} sortBy
 * @returns {$CancellablePromise<void>}
 */
export function GetProcessListAsync(connectKey, sortBy) {
    return $Call.ByID(4208171967, connectKey, sortBy);
}

/**
 * @param {string} connectKey
 * @param {string} sortBy
 * @param {string} platform
 * @returns {$CancellablePromise<void>}
 */
export function GetProcessListAsyncByPlatform(connectKey, sortBy, platform) {
    return $Call.ByID(2602785249, connectKey, sortBy, platform);
}

/**
 * @param {string} connectKey
 * @param {string} sortBy
 * @param {string} platform
 * @returns {$CancellablePromise<$models.ProcessListResult | null>}
 */
export function GetProcessListByPlatform(connectKey, sortBy, platform) {
    return $Call.ByID(3620183799, connectKey, sortBy, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType64($result);
    }));
}

/**
 * GetProcessMemoryDetail 获取进程内存详情
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<hdc$0.ProcessMemoryDetail | null>}
 */
export function GetProcessMemoryDetail(connectKey, pid) {
    return $Call.ByID(2259922387, connectKey, pid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType66($result);
    }));
}

/**
 * GetRequests 获取请求列表（合并该设备所有端口的请求）
 * @param {string} deviceId
 * @param {number} limit
 * @returns {$CancellablePromise<$models.NetworkRequest[]>}
 */
export function GetRequests(deviceId, limit) {
    return $Call.ByID(197645306, deviceId, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType68($result);
    }));
}

/**
 * GetScreenRecordHistory 获取录屏历史记录
 * @param {string} savePath
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetScreenRecordHistory(savePath) {
    return $Call.ByID(3906504351, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetScreenshotHistory 获取截图历史记录
 * @param {string} savePath
 * @returns {$CancellablePromise<{ [_ in string]?: any }[]>}
 */
export function GetScreenshotHistory(savePath) {
    return $Call.ByID(1567488824, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetStorageInfo 获取存储信息（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.StorageInfo | null>}
 */
export function GetStorageInfo(connectKey) {
    return $Call.ByID(924530493, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType70($result);
    }));
}

/**
 * GetStorageInfoByPlatform 获取存储信息（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.StorageInfo | null>}
 */
export function GetStorageInfoByPlatform(connectKey, platform) {
    return $Call.ByID(2730517375, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType72($result);
    }));
}

/**
 * GetSystemProperties 获取所有系统属性（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.SystemProperties>}
 */
export function GetSystemProperties(connectKey) {
    return $Call.ByID(309410276, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType73($result);
    }));
}

/**
 * GetSystemPropertiesByPlatform 获取系统属性（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.SystemProperties>}
 */
export function GetSystemPropertiesByPlatform(connectKey, platform) {
    return $Call.ByID(2364272342, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType74($result);
    }));
}

/**
 * GetSystemRuntime 获取系统运行信息（兼容旧 API，默认鸿蒙）
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.SystemRuntime | null>}
 */
export function GetSystemRuntime(connectKey) {
    return $Call.ByID(125130451, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType76($result);
    }));
}

/**
 * GetSystemRuntimeByPlatform 获取系统运行信息（根据平台路由）
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<device$0.SystemRuntime | null>}
 */
export function GetSystemRuntimeByPlatform(connectKey, platform) {
    return $Call.ByID(1248488061, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType78($result);
    }));
}

/**
 * GetUptimeInfo 获取系统运行时间信息
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetUptimeInfo(connectKey) {
    return $Call.ByID(3025861228, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetUserDocumentsDirectory 获取用户文档目录
 * @returns {$CancellablePromise<string>}
 */
export function GetUserDocumentsDirectory() {
    return $Call.ByID(2123182002);
}

/**
 * GetUserDownloadsDirectory 获取用户下载目录
 * @returns {$CancellablePromise<string>}
 */
export function GetUserDownloadsDirectory() {
    return $Call.ByID(3183741619);
}

/**
 * GetUserHomeDirectory 获取用户主目录
 * @returns {$CancellablePromise<string>}
 */
export function GetUserHomeDirectory() {
    return $Call.ByID(2134063239);
}

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2820628409, name);
}

/**
 * InstallApp 安装应用，支持ZIP和GZIP压缩包
 * @param {string} connectKey
 * @param {string} filePath
 * @param {boolean} replace
 * @param {boolean} sharedBundle
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function InstallApp(connectKey, filePath, replace, sharedBundle) {
    return $Call.ByID(1123486846, connectKey, filePath, replace, sharedBundle).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * IsAndroidDevice 检测设备是否为 Android 设备
 * @param {string} deviceId
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAndroidDevice(deviceId) {
    return $Call.ByID(3197854557, deviceId);
}

/**
 * IsDeviceRooted 检测设备是否已 Root
 * @param {string} deviceId
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDeviceRooted(deviceId) {
    return $Call.ByID(520097471, deviceId);
}

/**
 * IsPanelWindowOpen 判断指定菜单的独立窗口是否已打开
 * @param {string} menuId
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPanelWindowOpen(menuId) {
    return $Call.ByID(3680742458, menuId);
}

/**
 * @param {string} connectKey
 * @param {number} pid
 * @param {boolean} force
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function KillProcess(connectKey, pid, force) {
    return $Call.ByID(3123128197, connectKey, pid, force).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} connectKey
 * @param {number} pid
 * @param {boolean} force
 * @param {string} platform
 * @returns {$CancellablePromise<$models.CommandResult | null>}
 */
export function KillProcessByPlatform(connectKey, pid, force, platform) {
    return $Call.ByID(2296614663, connectKey, pid, force, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * KillServer 终止服务
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function KillServer() {
    return $Call.ByID(4190151411).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListAdbDevices 获取安卓设备列表
 * @param {boolean} verbose
 * @returns {$CancellablePromise<device$0.Device[]>}
 */
export function ListAdbDevices(verbose) {
    return $Call.ByID(156566624, verbose).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType80($result);
    }));
}

/**
 * ListAllDevices 获取所有设备（鸿蒙 + 安卓）
 * @param {boolean} verbose
 * @returns {$CancellablePromise<device$0.Device[]>}
 */
export function ListAllDevices(verbose) {
    return $Call.ByID(2967398830, verbose).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType80($result);
    }));
}

/**
 * ListDeviceDirectory 列出设备目录内容
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} path
 * @param {string} platform
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ListDeviceDirectory(connectKey, path, platform) {
    return $Call.ByID(1358629017, connectKey, path, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListDevices 获取设备列表（基础信息）
 * @param {boolean} verbose
 * @returns {$CancellablePromise<hdc$0.HdcDevice[]>}
 */
export function ListDevices(verbose) {
    return $Call.ByID(700490603, verbose).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType82($result);
    }));
}

/**
 * ListDevicesWithInfo 获取设备列表（包含产品名称、型号等）
 * @returns {$CancellablePromise<hdc$0.HdcDevice[]>}
 */
export function ListDevicesWithInfo() {
    return $Call.ByID(1754884039).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType82($result);
    }));
}

/**
 * ListLocalDirectory 列出本地目录内容
 * @param {string} path
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ListLocalDirectory(path) {
    return $Call.ByID(1769856554, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListPortForwards 获取所有端口转发列表
 * @returns {$CancellablePromise<$models.PortForwardItem[]>}
 */
export function ListPortForwards() {
    return $Call.ByID(2913808025).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType84($result);
    }));
}

/**
 * OpenBrowser 在系统浏览器中打开URL
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenBrowser(url) {
    return $Call.ByID(2276827160, url);
}

/**
 * OpenFileInSystem 在系统文件管理器中打开文件或文件夹
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenFileInSystem(filePath) {
    return $Call.ByID(1173626248, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenFolder 在文件管理器中打开指定文件夹
 * @param {string} folderPath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenFolder(folderPath) {
    return $Call.ByID(1922245396, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenLogFile 在系统日志查看器中打开日志文件
 * macOS 上使用 Console.app 打开，支持实时流读取
 * @param {string} filePath
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function OpenLogFile(filePath) {
    return $Call.ByID(3708622932, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * OpenPanelWindow 在独立窗口中打开指定菜单页
 * menuId: 菜单 ID（如 device-overview）
 * title: 窗口标题
 * 若该菜单的独立窗口已存在，则聚焦显示；否则创建新窗口
 * @param {string} menuId
 * @param {string} title
 * @returns {$CancellablePromise<boolean>}
 */
export function OpenPanelWindow(menuId, title) {
    return $Call.ByID(3012223394, menuId, title);
}

/**
 * OpenScreenshotFile 在文件管理器中打开截图文件并定位
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenScreenshotFile(filePath) {
    return $Call.ByID(228531874, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenScreenshotFolder 在文件管理器中打开截图目录
 * @param {string} savePath
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function OpenScreenshotFolder(savePath) {
    return $Call.ByID(3244782592, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ParseAppPackageInfo 解析安装包信息（支持 HAP/APK 格式）
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.InstallPackageInfo | null>}
 */
export function ParseAppPackageInfo(filePath) {
    return $Call.ByID(389740578, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType86($result);
    }));
}

/**
 * ParseHapAppInfo 解析 HAP 应用信息（向后兼容）
 * Deprecated: 使用 ParseAppPackageInfo 代替
 * @param {string} filePath
 * @returns {$CancellablePromise<hdc$0.HapAppInfo | null>}
 */
export function ParseHapAppInfo(filePath) {
    return $Call.ByID(2383677915, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType86($result);
    }));
}

/**
 * @param {string} deviceSn
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function PressBack(deviceSn) {
    return $Call.ByID(1466384008, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} deviceSn
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function PressHome(deviceSn) {
    return $Call.ByID(929152932, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} deviceSn
 * @param {number} keyCode
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function PressKey(deviceSn, keyCode) {
    return $Call.ByID(3782947414, deviceSn, keyCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * PullFileFromDevice 从设备拉取文件
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} remotePath
 * @param {string} localPath
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function PullFileFromDevice(connectKey, remotePath, localPath, platform) {
    return $Call.ByID(232583903, connectKey, remotePath, localPath, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * PushAndroidMockConfigToClient 推送 Mock 配置到 Android JVMTI Agent
 * @param {string} deviceId
 * @param {string} packageName
 * @param {string} configJson
 * @returns {$CancellablePromise<void>}
 */
export function PushAndroidMockConfigToClient(deviceId, packageName, configJson) {
    return $Call.ByID(1561987169, deviceId, packageName, configJson);
}

/**
 * PushFileToDevice 推送文件到设备
 * platform: "harmonyos" 或 "android"
 * @param {string} connectKey
 * @param {string} localPath
 * @param {string} remotePath
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function PushFileToDevice(connectKey, localPath, remotePath, platform) {
    return $Call.ByID(3346153765, connectKey, localPath, remotePath, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * PushMockConfigToClient 推送Mock配置到Sophon客户端
 * @param {string} deviceId
 * @param {string} configJson
 * @returns {$CancellablePromise<void>}
 */
export function PushMockConfigToClient(deviceId, configJson) {
    return $Call.ByID(1597236662, deviceId, configJson);
}

/**
 * QueryScreenRecordFile 不断查询录屏文件位置，直到找到文件
 * @param {string} connectKey
 * @param {string} fileName
 * @param {number} maxWaitTime
 * @param {number} checkInterval
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function QueryScreenRecordFile(connectKey, fileName, maxWaitTime, checkInterval) {
    return $Call.ByID(2837447451, connectKey, fileName, maxWaitTime, checkInterval).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ReadImageAsBase64 读取图片为 base64
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadImageAsBase64(filePath) {
    return $Call.ByID(3852543598, filePath);
}

/**
 * RemovePortForward 删除端口转发
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function RemovePortForward(localPort, devicePort) {
    return $Call.ByID(759391216, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ResizeShell 调整 Shell 终端大小
 * @param {string} shellId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeShell(shellId, cols, rows) {
    return $Call.ByID(3459881586, shellId, cols, rows);
}

/**
 * RestartServer 重启服务
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function RestartServer() {
    return $Call.ByID(3895595584).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} content
 * @param {string} defaultFileName
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function SaveLogsToFile(content, defaultFileName) {
    return $Call.ByID(807255669, content, defaultFileName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SaveTextFile 将文本内容保存到 ~/Documents/Hadice/ 下的指定相对路径。
 * filename: 文件名或相对路径（如 "network/capture_harmony_demo_20260730141620.csv"）
 * content: 文件内容
 * 返回保存的完整路径
 * @param {string} filename
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveTextFile(filename, content) {
    return $Call.ByID(1731107096, filename, content);
}

/**
 * Scroll 滚动事件
 * HarmonyOS: 使用 uitest uiInput scroll (暂不支持，使用 swipe 模拟)
 * Android: 使用 scrcpy 控制通道 SendScrollEvent
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @param {number} hscroll
 * @param {number} vscroll
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function Scroll(deviceSn, x, y, hscroll, vscroll) {
    return $Call.ByID(4203914505, deviceSn, x, y, hscroll, vscroll).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SelectHapFile 选择安装包文件
 * connectKey: 设备连接标识，用于判断设备平台
 * @param {string} connectKey
 * @returns {$CancellablePromise<string>}
 */
export function SelectHapFile(connectKey) {
    return $Call.ByID(477435511, connectKey);
}

/**
 * SelectScreenshotPath 选择截图保存路径
 * @returns {$CancellablePromise<string>}
 */
export function SelectScreenshotPath() {
    return $Call.ByID(831565491);
}

/**
 * SetPosthogDistinctId 设置用户 distinct_id（由前端调用）
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetPosthogDistinctId(id) {
    return $Call.ByID(3326459025, id);
}

/**
 * StartAndroidNetworkCapture 启动 Android 网络抓包
 * @param {string} deviceId
 * @param {string} packageName
 * @param {number} pid
 * @param {number} localPort
 * @returns {$CancellablePromise<void>}
 */
export function StartAndroidNetworkCapture(deviceId, packageName, pid, localPort) {
    return $Call.ByID(3744098227, deviceId, packageName, pid, localPort);
}

/**
 * StartApp 启动应用
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StartApp(connectKey, packageName) {
    return $Call.ByID(1161678279, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StartAppByPlatform 根据平台启动应用
 * @param {string} connectKey
 * @param {string} packageName
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StartAppByPlatform(connectKey, packageName, platform) {
    return $Call.ByID(4046798281, connectKey, packageName, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StartCapture 开始抓包
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StartCapture(deviceId, localPort, devicePort) {
    return $Call.ByID(317097558, deviceId, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartCaptureServer 开始抓包（新架构：Hadice作为服务器）
 * @param {string} deviceId
 * @param {number} localPort
 * @param {number} devicePort
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StartCaptureServer(deviceId, localPort, devicePort) {
    return $Call.ByID(1030863057, deviceId, localPort, devicePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartHiProfilerCapture 启动 HiProfiler 抓包
 * @param {string} deviceId
 * @param {number} pid
 * @param {string} bundleName
 * @param {string} processName
 * @returns {$CancellablePromise<void>}
 */
export function StartHiProfilerCapture(deviceId, pid, bundleName, processName) {
    return $Call.ByID(2458837788, deviceId, pid, bundleName, processName);
}

/**
 * @param {string} connectKey
 * @param {{ [_ in string]?: any }} options
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StartHilogStream(connectKey, options) {
    return $Call.ByID(2641361047, connectKey, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StartIpcStat 开始 IPC 统计
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function StartIpcStat(connectKey, pid) {
    return $Call.ByID(3790979896, connectKey, pid);
}

/**
 * @param {string} connectKey
 * @param {string} platform
 * @param {{ [_ in string]?: any }} options
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StartLogStream(connectKey, platform, options) {
    return $Call.ByID(3434582134, connectKey, platform, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} deviceId
 * @param {{ [_ in string]?: any }} options
 * @returns {$CancellablePromise<adb$0.AdbResult | null>}
 */
export function StartLogcatStream(deviceId, options) {
    return $Call.ByID(3828877810, deviceId, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * StartPhoneAgent 启动PhoneAgent
 * config: Agent配置
 * 返回会话ID和错误
 * @param {phoneAgent$0.AgentConfig} config
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StartPhoneAgent(config) {
    return $Call.ByID(1248407409, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartScreenMirror 开始投屏
 * 
 * HarmonyOS 实现方式：使用 hypium-driver + agent.so + RPC 模式
 * Android 实现方式：使用 scrcpy + FFmpeg 管道模式
 * scale: 缩放比例（0.0-1.0），默认 0.6
 * @param {string} deviceSn
 * @param {number} scale
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StartScreenMirror(deviceSn, scale) {
    return $Call.ByID(3859390787, deviceSn, scale).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartScreenRecord 开始录屏
 * @param {string} connectKey
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StartScreenRecord(connectKey) {
    return $Call.ByID(199315045, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StartServer 启动服务
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StartServer() {
    return $Call.ByID(89399095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StartShell 启动一个本地 Shell 终端
 * shellId: Shell 进程的唯一标识符
 * @param {string} shellId
 * @returns {$CancellablePromise<boolean>}
 */
export function StartShell(shellId) {
    return $Call.ByID(3956221126, shellId);
}

/**
 * StopAllAndroidCaptures 停止指定设备的所有 Android 抓包会话（按设备 ID 清理，不依赖 packageName）
 * 用于强制停止/兜底场景：当 packageName 带有残留字符导致 sessionKey 不匹配时仍可清理
 * @param {string} deviceId
 * @returns {$CancellablePromise<number>}
 */
export function StopAllAndroidCaptures(deviceId) {
    return $Call.ByID(2515818177, deviceId);
}

/**
 * StopAllHiProfilerCaptures 停止指定设备由 Hadice 管理的全部 HiProfiler 会话。
 * @param {string} deviceId
 * @returns {$CancellablePromise<number>}
 */
export function StopAllHiProfilerCaptures(deviceId) {
    return $Call.ByID(1097000062, deviceId);
}

/**
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopAllHilogStreams() {
    return $Call.ByID(3222221859).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<adb$0.AdbResult | null>}
 */
export function StopAllLogcatStreams() {
    return $Call.ByID(905304130).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * StopAllShells 停止所有 Shell 进程
 * @returns {$CancellablePromise<void>}
 */
export function StopAllShells() {
    return $Call.ByID(50652588);
}

/**
 * StopAndroidNetworkCapture 停止 Android 网络抓包
 * @param {string} deviceId
 * @param {string} packageName
 * @returns {$CancellablePromise<void>}
 */
export function StopAndroidNetworkCapture(deviceId, packageName) {
    return $Call.ByID(2527214999, deviceId, packageName);
}

/**
 * StopApp 停止应用
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopApp(connectKey, packageName) {
    return $Call.ByID(823232027, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopAppByPlatform 根据平台停止应用
 * @param {string} connectKey
 * @param {string} packageName
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopAppByPlatform(connectKey, packageName, platform) {
    return $Call.ByID(1274163749, connectKey, packageName, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopCapture 停止抓包（停止指定设备的所有端口抓包）
 * @param {string} deviceId
 * @returns {$CancellablePromise<void>}
 */
export function StopCapture(deviceId) {
    return $Call.ByID(1152162898, deviceId);
}

/**
 * StopCapturePort 停止指定端口的抓包
 * @param {string} deviceId
 * @param {number} localPort
 * @returns {$CancellablePromise<void>}
 */
export function StopCapturePort(deviceId, localPort) {
    return $Call.ByID(3136414333, deviceId, localPort);
}

/**
 * StopCaptureServer 停止抓包服务器（新架构）
 * 注意：停止服务器时不会删除服务器对象，以保留历史请求记录
 * @param {string} deviceId
 * @returns {$CancellablePromise<void>}
 */
export function StopCaptureServer(deviceId) {
    return $Call.ByID(3234612069, deviceId);
}

/**
 * StopHiProfilerCapture 停止 HiProfiler 抓包
 * @param {string} deviceId
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function StopHiProfilerCapture(deviceId, pid) {
    return $Call.ByID(1676848904, deviceId, pid);
}

/**
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopHilogStream(connectKey) {
    return $Call.ByID(2166192667, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopIpcStat 停止 IPC 统计
 * @param {string} connectKey
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function StopIpcStat(connectKey, pid) {
    return $Call.ByID(813354156, connectKey, pid);
}

/**
 * @param {string} connectKey
 * @param {string} platform
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StopLogStream(connectKey, platform) {
    return $Call.ByID(1007514602, connectKey, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} deviceId
 * @returns {$CancellablePromise<adb$0.AdbResult | null>}
 */
export function StopLogcatStream(deviceId) {
    return $Call.ByID(1152566694, deviceId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * StopPhoneAgent 停止PhoneAgent
 * sessionID: 会话ID
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StopPhoneAgent(sessionID) {
    return $Call.ByID(915681413, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StopScreenMirror 停止投屏
 * @param {string} deviceSn
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function StopScreenMirror(deviceSn) {
    return $Call.ByID(2535289159, deviceSn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StopScreenRecord 停止录屏
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function StopScreenRecord(connectKey) {
    return $Call.ByID(1840820097, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * StopShell 停止 Shell 进程
 * @param {string} shellId
 * @returns {$CancellablePromise<void>}
 */
export function StopShell(shellId) {
    return $Call.ByID(808586850, shellId);
}

/**
 * TakeScreenshot 截取设备屏幕截图
 * @param {string} connectKey
 * @param {string} savePath
 * @param {string} format
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function TakeScreenshot(connectKey, savePath, format) {
    return $Call.ByID(2960633239, connectKey, savePath, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TestConnection 测试连接
 * @param {number} localPort
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function TestConnection(localPort) {
    return $Call.ByID(135248668, localPort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchDown 触摸按下事件
 * HarmonyOS: 使用 uitest uiInput longClick 模拟按下
 * Android: 使用 scrcpy 控制通道发送 DOWN 事件
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function TouchDown(deviceSn, x, y) {
    return $Call.ByID(2965111083, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchMove 触摸移动事件
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function TouchMove(deviceSn, x, y) {
    return $Call.ByID(2306873878, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchMoveFromTo 触摸从起点移动到终点
 * HarmonyOS: 使用 uitest uiInput swipe
 * Android: 使用 scrcpy 控制通道或 input swipe
 * @param {string} deviceSn
 * @param {number} startX
 * @param {number} startY
 * @param {number} endX
 * @param {number} endY
 * @param {number} smoothTime
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function TouchMoveFromTo(deviceSn, startX, startY, endX, endY, smoothTime) {
    return $Call.ByID(1056398471, deviceSn, startX, startY, endX, endY, smoothTime).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TouchUp 触摸抬起事件
 * @param {string} deviceSn
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function TouchUp(deviceSn, x, y) {
    return $Call.ByID(4258587082, deviceSn, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * UninstallApp 卸载应用
 * @param {string} connectKey
 * @param {string} packageName
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function UninstallApp(connectKey, packageName) {
    return $Call.ByID(2326448121, connectKey, packageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * UninstallAppByPlatform 根据平台卸载应用
 * @param {string} connectKey
 * @param {string} packageName
 * @param {string} platform
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function UninstallAppByPlatform(connectKey, packageName, platform) {
    return $Call.ByID(4125878243, connectKey, packageName, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * WaitForDevice 等待设备连接
 * @param {string} connectKey
 * @returns {$CancellablePromise<hdc$0.HdcResult | null>}
 */
export function WaitForDevice(connectKey) {
    return $Call.ByID(3786752182, connectKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * WriteToShell 向 Shell 写入数据
 * @param {string} shellId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteToShell(shellId, data) {
    return $Call.ByID(22271860, shellId, data);
}

// Private type creation functions
const $$createType0 = device$0.CommandResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PortForwardStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = hdc$0.HdcResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.WirelessDebugResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = adb$0.AdbResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.CommandResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = adb$0.AndroidAppListResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType5);
const $$createType17 = hdc$0.AppListResult.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = hdc$0.BatteryInfo.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = device$0.BatteryInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = hdc$0.CpuDetailInfo.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = hdc$0.CpuFreqInfo.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = hdc$0.CpuUsageInfo.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = device$0.CpuUsageInfo.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = hdc$0.DeviceDetailInfo.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = device$0.DeviceDetailInfo.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = hdc$0.DeviceInfo.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = $models.DisplaySize.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = hdc$0.FaultLogEntry.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = hdc$0.GraphicsInfo.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = hdc$0.IpcStatInfo.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = hdc$0.MemoryDetailInfo.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = hdc$0.MemoryInfo.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = device$0.MemoryInfo.createFrom;
const $$createType50 = $Create.Nullable($$createType49);
const $$createType51 = hdc$0.NetworkInfo.createFrom;
const $$createType52 = $Create.Array($$createType51);
const $$createType53 = device$0.NetworkInfo.createFrom;
const $$createType54 = $Create.Array($$createType53);
const $$createType55 = hdc$0.NetworkTrafficInfo.createFrom;
const $$createType56 = $Create.Array($$createType55);
const $$createType57 = hdc$0.OnlineAppInfo.createFrom;
const $$createType58 = $Create.Nullable($$createType57);
const $$createType59 = hdc$0.ProcessCpuEntry.createFrom;
const $$createType60 = $Create.Array($$createType59);
const $$createType61 = hdc$0.ProcessIOInfo.createFrom;
const $$createType62 = $Create.Nullable($$createType61);
const $$createType63 = $models.ProcessListResult.createFrom;
const $$createType64 = $Create.Nullable($$createType63);
const $$createType65 = hdc$0.ProcessMemoryDetail.createFrom;
const $$createType66 = $Create.Nullable($$createType65);
const $$createType67 = $models.NetworkRequest.createFrom;
const $$createType68 = $Create.Array($$createType67);
const $$createType69 = hdc$0.StorageInfo.createFrom;
const $$createType70 = $Create.Nullable($$createType69);
const $$createType71 = device$0.StorageInfo.createFrom;
const $$createType72 = $Create.Nullable($$createType71);
var $$createType73 = /** @type {(...args: any[]) => any} */(function $$initCreateType73(...args) {
    if ($$createType73 === $$initCreateType73) {
        $$createType73 = $$createType4;
    }
    return $$createType73(...args);
});
var $$createType74 = /** @type {(...args: any[]) => any} */(function $$initCreateType74(...args) {
    if ($$createType74 === $$initCreateType74) {
        $$createType74 = $$createType4;
    }
    return $$createType74(...args);
});
const $$createType75 = hdc$0.SystemRuntime.createFrom;
const $$createType76 = $Create.Nullable($$createType75);
const $$createType77 = device$0.SystemRuntime.createFrom;
const $$createType78 = $Create.Nullable($$createType77);
const $$createType79 = device$0.Device.createFrom;
const $$createType80 = $Create.Array($$createType79);
const $$createType81 = hdc$0.HdcDevice.createFrom;
const $$createType82 = $Create.Array($$createType81);
const $$createType83 = $models.PortForwardItem.createFrom;
const $$createType84 = $Create.Array($$createType83);
const $$createType85 = hdc$0.InstallPackageInfo.createFrom;
const $$createType86 = $Create.Nullable($$createType85);
