// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "./device/models.js";

export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

/**
 * DisplaySize 屏幕尺寸
 */
export class DisplaySize {
    /**
     * Creates a new DisplaySize instance.
     * @param {Partial<DisplaySize>} [$$source = {}] - The source object to create the DisplaySize.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplaySize instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DisplaySize}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisplaySize(/** @type {Partial<DisplaySize>} */($$parsedSource));
    }
}

/**
 * HttpExtra HTTP Extra信息
 */
export class HttpExtra {
    /**
     * Creates a new HttpExtra instance.
     * @param {Partial<HttpExtra>} [$$source = {}] - The source object to create the HttpExtra.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("reqTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reqTime"] = 0;
        }
        if (!("respTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["respTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpExtra instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HttpExtra}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HttpExtra(/** @type {Partial<HttpExtra>} */($$parsedSource));
    }
}

/**
 * NetworkRequest 网络请求数据
 */
export class NetworkRequest {
    /**
     * Creates a new NetworkRequest instance.
     * @param {Partial<NetworkRequest>} [$$source = {}] - The source object to create the NetworkRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fullUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["statusCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["requestHeaders"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["responseHeaders"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["requestBody"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["responseBody"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["rawData"] = undefined;
        }
        if (!("direction" in $$source)) {
            /**
             * request, response
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HttpExtra | null | undefined}
             */
            this["extra"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * URL Query Parameters (来自 data.request.params)
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["requestParams"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 请求基础 URL (来自 data.request.baseURL)
             * @member
             * @type {string | undefined}
             */
            this["baseURL"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 会话边界标记相关字段
             * 是否为会话边界标记
             * @member
             * @type {boolean | undefined}
             */
            this["isSessionBoundary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 边界类型: "disconnect"
             * @member
             * @type {string | undefined}
             */
            this["boundaryType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 客户端ID
             * @member
             * @type {string | undefined}
             */
            this["clientId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 边界信息描述
             * @member
             * @type {string | undefined}
             */
            this["boundaryMessage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkRequest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requestHeaders" in $$parsedSource) {
            $$parsedSource["requestHeaders"] = $$createField6_0($$parsedSource["requestHeaders"]);
        }
        if ("responseHeaders" in $$parsedSource) {
            $$parsedSource["responseHeaders"] = $$createField7_0($$parsedSource["responseHeaders"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField12_0($$parsedSource["extra"]);
        }
        if ("requestParams" in $$parsedSource) {
            $$parsedSource["requestParams"] = $$createField13_0($$parsedSource["requestParams"]);
        }
        return new NetworkRequest(/** @type {Partial<NetworkRequest>} */($$parsedSource));
    }
}

/**
 * PortForwardItem 端口转发项
 */
export class PortForwardItem {
    /**
     * Creates a new PortForwardItem instance.
     * @param {Partial<PortForwardItem>} [$$source = {}] - The source object to create the PortForwardItem.
     */
    constructor($$source = {}) {
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("devicePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["devicePort"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * Forward, Reverse
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForwardItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardItem(/** @type {Partial<PortForwardItem>} */($$parsedSource));
    }
}

/**
 * PortForwardStatus 端口转发状态
 */
export class PortForwardStatus {
    /**
     * Creates a new PortForwardStatus instance.
     * @param {Partial<PortForwardStatus>} [$$source = {}] - The source object to create the PortForwardStatus.
     */
    constructor($$source = {}) {
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (!("devicePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["devicePort"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * normal, error, not_configured
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForwardStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForwardStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForwardStatus(/** @type {Partial<PortForwardStatus>} */($$parsedSource));
    }
}

export class ProcessInfoUI {
    /**
     * Creates a new ProcessInfoUI instance.
     * @param {Partial<ProcessInfoUI>} [$$source = {}] - The source object to create the ProcessInfoUI.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("nice" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nice"] = 0;
        }
        if (!("virt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virt"] = "";
        }
        if (!("res" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["res"] = "";
        }
        if (!("shr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shr"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("cpuPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuPercent"] = 0;
        }
        if (!("memPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memPercent"] = 0;
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfoUI instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessInfoUI}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfoUI(/** @type {Partial<ProcessInfoUI>} */($$parsedSource));
    }
}

export class ProcessListResult {
    /**
     * Creates a new ProcessListResult instance.
     * @param {Partial<ProcessListResult>} [$$source = {}] - The source object to create the ProcessListResult.
     */
    constructor($$source = {}) {
        if (!("stats" in $$source)) {
            /**
             * @member
             * @type {ProcessStats}
             */
            this["stats"] = (new ProcessStats());
        }
        if (!("processes" in $$source)) {
            /**
             * @member
             * @type {ProcessInfoUI[]}
             */
            this["processes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessListResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField0_0($$parsedSource["stats"]);
        }
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField1_0($$parsedSource["processes"]);
        }
        return new ProcessListResult(/** @type {Partial<ProcessListResult>} */($$parsedSource));
    }
}

export class ProcessStats {
    /**
     * Creates a new ProcessStats instance.
     * @param {Partial<ProcessStats>} [$$source = {}] - The source object to create the ProcessStats.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["running"] = 0;
        }
        if (!("sleeping" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sleeping"] = 0;
        }
        if (!("stopped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["stopped"] = 0;
        }
        if (!("zombie" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["zombie"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessStats(/** @type {Partial<ProcessStats>} */($$parsedSource));
    }
}

export class WirelessDebugRequest {
    /**
     * Creates a new WirelessDebugRequest instance.
     * @param {Partial<WirelessDebugRequest>} [$$source = {}] - The source object to create the WirelessDebugRequest.
     */
    constructor($$source = {}) {
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pairPort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pairCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["connectPort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WirelessDebugRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WirelessDebugRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WirelessDebugRequest(/** @type {Partial<WirelessDebugRequest>} */($$parsedSource));
    }
}

export class WirelessDebugResult {
    /**
     * Creates a new WirelessDebugResult instance.
     * @param {Partial<WirelessDebugResult>} [$$source = {}] - The source object to create the WirelessDebugResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["connectKey"] = undefined;
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {device$0.Platform}
             */
            this["platform"] = device$0.Platform.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WirelessDebugResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WirelessDebugResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WirelessDebugResult(/** @type {Partial<WirelessDebugResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = HttpExtra.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = ProcessStats.createFrom;
const $$createType5 = ProcessInfoUI.createFrom;
const $$createType6 = $Create.Array($$createType5);
