// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CommandResult 命令执行结果
 */
export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

/**
 * Device 统一设备信息
 */
export class Device {
    /**
     * Creates a new Device instance.
     * @param {Partial<Device>} [$$source = {}] - The source object to create the Device.
     */
    constructor($$source = {}) {
        if (!("connectKey" in $$source)) {
            /**
             * 设备标识符
             * @member
             * @type {string}
             */
            this["connectKey"] = "";
        }
        if (!("connectionType" in $$source)) {
            /**
             * 连接类型：USB 或 TCP
             * @member
             * @type {string}
             */
            this["connectionType"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 连接状态
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 设备名称
             * @member
             * @type {string | undefined}
             */
            this["deviceName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 产品名称
             * @member
             * @type {string | undefined}
             */
            this["productName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 产品型号
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 显示名称
             * @member
             * @type {string | undefined}
             */
            this["displayName"] = undefined;
        }
        if (!("platform" in $$source)) {
            /**
             * 平台：harmonyos 或 android
             * @member
             * @type {Platform}
             */
            this["platform"] = Platform.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Device}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Device(/** @type {Partial<Device>} */($$parsedSource));
    }
}

/**
 * Platform 设备平台类型
 * @readonly
 * @enum {string}
 */
export const Platform = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlatformHarmonyOS: "harmonyos",
    PlatformAndroid: "android",
};
